-- Registro comun de iconos de contenido. Las fuentes de datos lo rellenan
-- por identificador estable; los nombres solo se usan como fallback visual.
HarfordIconCatalog = HarfordIconCatalog or {}
local Catalog = HarfordIconCatalog

Catalog.names = {
    ["absolucion encadenar no muertos"] = "spell_nature_slow",
    ["absorber elementos"] = "ability_shaman_echooftheelements",
    ["accion astuta"] = "ability_rogue_fleetfooted",
    ["acuajet"] = "inv_weapon_rifle_33",
    ["adaptacion salvaje"] = "eps_wow_wildstalkr",
    ["afinidad arcana"] = "ability_racial_arcaneaffinity",
    ["afinidad elemental"] = "ability_shawaterelemental_reform",
    ["afinidad feral frenesi"] = "ability_druid_primaltenacity",
    ["afinidades salvajes"] = "ability_druid_earthandsky",
    ["agarre de la muerte"] = "spell_deathknight_strangulate",
    ["ahuyentar el mal"] = "ability_paladin_turnevil",
    ["alacridad"] = "rogue_burstofspeed",
    ["alarma"] = "inv_misc_bell_green",
    ["antarbol"] = "ability_druid_treeoflife",
    ["apariencia falsa"] = "ability_druid_forceofnature",
    ["aprender hechizos"] = "spell_mage_presenceofmind",
    ["arma espiritual"] = "inv_legendary_sword",
    ["arrepentimiento"] = "spell_holy_prayerofhealing",
    ["arrollar"] = "ability_warrior_unrelentingassault",
    ["artista del escape"] = "eps_bg3_sprint",
    ["ataque furtivo"] = "ability_rogue_bladetwisting",
    ["autoridad de la orden: espada de ebano"] = "inv_jewelry_talisman_12",
    ["autoridad del capitan harford"] = "achievement_bg_3flagcap_nodeaths",
    ["auxilio"] = "eps_bg3_nightsongaidblue",
    ["bendicion"] = "eps_bg3_bless",
    ["brazos de hadar"] = "eps_bg3_armsofhadar",
    ["caida de pluma"] = "inv_feather_04",
    ["cambio de forma"] = "ability_druid_catform",
    ["canalizar divinidad"] = "spell_holy_lightsgrace",
    ["carga"] = "ability_warrior_charge",
    ["castigo abrasador"] = "ability_paladin_bladeofjustice",
    ["ceremonia"] = "eps_arc_book_priest1",
    ["choque elemental"] = "ability_shaman_echooftheelements",
    ["conjuracion de hechizos"] = "ability_druid_cresentburn",
    ["conocimiento antiguo de eldre'thalas"] = "achievements_zone_azsuna",
    ["conocimientos del artifice"] = "inv_misc_enggizmos_12",
    ["controlar llamas"] = "inv_elemental_mote_fire01",
    ["copiar un conjuro al libro"] = "inv_inscription_darkmooncard_putrescence",
    ["crear fogata"] = "inv_magemount_fire",
    ["crear o destruir agua"] = "icon_petfamily_water",
    ["cuchillo de hielo"] = "ability_paladin_bladeofjusticeblue",
    ["curar heridas"] = "eps_bg3_heal",
    ["defensa sin armadura"] = "inv_leather_raiddemonhunter_q_02helm",
    ["desarme"] = "ability_warrior_disarm",
    ["descarga de fuego"] = "spell_fire_flamebolt",
    ["descarga relampago"] = "ability_vehicle_electrocharge",
    ["desgarrar mente"] = "spell_shadow_mindflay",
    ["detectar magia 1/dia"] = "ability_monk_forcesphere_arcane",
    ["detectar venenos y enfermedades"] = "spell_shadow_detectinvisibility",
    ["determinacion"] = "ability_warrior_rallyingcry",
    ["devocion"] = "spell_holy_fanaticism",
    ["disco flotante de tenser"] = "creatureportrait_nexus_floating_disc",
    ["disfrazarse"] = "ability_rogue_disguise",
    ["dos formas"] = "eps_wc3h_worgencurse",
    ["dote centinela"] = "ability_warrior_revenge",
    ["dote observador"] = "ability_eyeoftheowl",
    ["drenar vida"] = "w3reforgedlifedrain",
    ["druidico"] = "ability_druid_lunarguidance",
    ["duelo forzado"] = "eps_lol_tft_duelistemblem",
    ["ecos de fe"] = "hots_anduin_holywordsalvation",
    ["embestida"] = "ability_druid_mangle",
    ["encontrar familiar"] = "eps_bg3_callanimals",
    ["endurecido por la guerra"] = "ability_pvp_hardiness",
    ["energia"] = "ability_rogue_vigor",
    ["enmaranar"] = "inv_misc_root_01",
    ["entender idiomas"] = "inv_misc_note_05",
    -- El rasgo de raza/trasfondo que lista los idiomas que hablas. Las razas lo llaman
    -- "Idiomas" y varios trasfondos "Idioma"; ambas formas usan el mismo icono.
    ["idioma"] = "inv_misc_note_05",
    ["idiomas"] = "inv_misc_note_05",
    ["erudito arcano"] = "spell_holy_arcaneintellect",
    ["escritura magica oculta"] = "inv_glyph_primemage",
    ["escucha resonante conejil"] = "inv_misc_rabbit_ears",
    ["escudo"] = "eps_lol_sivir_spellshield",
    ["escudo de fe"] = "eps_bg3_shieldoffaith",
    ["escudo de relampagos"] = "spell_nature_lightningshield",
    ["escudo de sangre"] = "artifactability_blooddeathknight_umbilicuseternus",
    ["espiral de la muerte"] = "spell_shadow_deathcoil",
    ["espiritu curativo"] = "spell_animaardenweald_orb",
    ["espiritu harford"] = "inv_tabard_duelersguild",
    ["espiritu humano"] = "inv_enchant_shardbrilliantsmall",
    ["espiritu mestizo"] = "inv_enchant_shardbrilliantsmall",
    ["estallido de espadas"] = "inv_throwingknife_01",
    ["estilo de combate combate con dos armas"] = "ability_dualwield",
    ["estilo de combate defensa"] = "ability_defend",
    ["estilo de combate duelo"] = "eps_lol_tft_duelistemblem",
    ["estilo de combate gran arma"] = "ability_warrior_savageblow",
    ["experto marcial"] = "ability_monk_jab",
    ["explosion mental"] = "spell_shadow_unholyfrenzy",
    ["exponer armadura"] = "ability_rogue_dismantle",
    ["favor divino"] = "ability_paladin_selflesshealer",
    ["fervor temible"] = "ability_deathknight_deathscaress",
    ["filo atronador"] = "eps_lol_item_sheen",
    ["filo de llamas verdes"] = "inv_sword_1h_broker2boss_d_01_green",
    ["fuente de magia"] = "spell_shadow_manafeed",
    ["furia"] = "ability_warrior_innerrage",
    ["fusion con las sombras"] = "ability_racial_shadowmeld",
    ["garra"] = "eps_wc3_eattree",
    ["garrote"] = "ability_rogue_garrote",
    ["gato"] = "ability_druid_catform",
    ["generador de luz hiperorganica"] = "inv_misc_enggizmos_24",
    ["golpe de escarcha"] = "spell_deathknight_empowerruneblade2",
    ["golpe del cruzado"] = "inv_sword_08",
    ["golpe heroico"] = "ability_warrior_punishingblow",
    ["golpe runico"] = "achievement_dungeon_icecrown_frostmourne",
    ["gourmet"] = "pandarenracial_gourmand",
    ["guardia de cuchillas"] = "eps_lol_rk_ahri_ward",
    ["guia"] = "eps_bg3_combatguidance",
    ["guia ancestral"] = "ability_shaman_ancestralguidance",
    ["hablar con bestias"] = "eps_bg3_speakwithanimals",
    ["heroismo"] = "ability_shaman_heroism",
    ["himno divino"] = "ability_priest_heavanlyvoice",
    ["identificar"] = "eps_bg3_identify",
    ["ilusion menor"] = "spell_magic_lesserinvisibilty",
    ["imposicion de manos"] = "spell_holy_layonhands",
    ["infligir heridas"] = "eps_bg3_inflictwounds",
    ["iniciacion illidari"] = "ability_demonhunter_eyeofleotheras",
    ["intrepido"] = "ability_warrior_revenge",
    ["investigador"] = "w3reforgedarcanescroll",
    ["ira"] = "ability_warrior_innerrage",
    ["kalimag"] = "eps_lol_taliyah_unraveledearth",
    ["lechucico lunar"] = "ability_druid_improvedmoonkinform",
    ["legado del vacio"] = "hots_malzahar_voidshift",
    ["legado elficocrear fogata"] = "achievement_zone_eversongwoods",
    ["legado thalassianoreparar"] = "achievement_zone_eversongwoods",
    ["libro de conjuros"] = "garrison_building_magetower",
    ["llama sagrada"] = "eps_bg3_sacredflameholy",
    ["llama vil"] = "eps_bg3_fireballfel",
    ["llamado divino sagrado"] = "ability_paladin_holyavenger",
    ["llamas del caos"] = "spell_fire_felfire",
    ["localizar objeto"] = "inv_misc_spyglass_03",
    ["luz"] = "eps_lol_leona_sunlightold",
    ["magia vil"] = "eps_wc3h_felpower",
    ["mano de mago"] = "eps_bg3_magehand",
    ["manos ardientes"] = "eps_bg3_flamingfist",
    ["maquina de matar"] = "inv_sword_122",
    ["marca de ursoc"] = "eps_lol_volibear_frenzyold",
    ["mascara de lo salvaje"] = "ability_ambush",
    ["mejoras mecanicas"] = "inv_mechagon_wrench",
    ["mensaje"] = "achievement_guildperk_gmail",
    ["metamorfosis"] = "ability_demonhunter_metamorphasisdps",
    ["misivas secretas"] = "archaeology_5_0_changkiboard",
    ["modo de mantenimiento"] = "ability_siege_engineer_automatic_repair_beam",
    ["momentum"] = "ability_demonhunter_doublejump",
    ["mordida"] = "inv_misc_monsterfang_02",
    ["mordida de demonio"] = "ability_demonhunter_torment",
    ["mordisco"] = "inv_misc_monsterfang_02",
    ["multiataque"] = "ability_druid_mangle2",
    ["mutilar"] = "ability_rogue_shadowstrikes",
    ["nube de oscurecimiento"] = "spell_holiday_tow_spicecloud",
    ["oido y olfato agudo"] = "ability_shaman_freedomwolf",
    ["oidos atentos"] = "inv_misc_ear_human_01",
    ["olfato agudo"] = "ability_hunter_catlikereflexes",
    ["omniherramienta"] = "inv_axe_1h_mechagnome_c_01",
    ["orden imperiosa"] = "ability_warrior_rallyingcry",
    ["orden oscura"] = "spell_nature_shamanrage",
    ["oso"] = "ability_racial_bearform",
    ["palabra de curacion"] = "eps_bg3_healingword",
    ["palabra de las sombras dolor"] = "spell_shadow_shadowwordpain",
    ["palabra de las sombras muerte"] = "spell_shadow_demonicfortitude",
    ["palma fulminante"] = "pandarenracial_quiveringpain",
    ["paz interior"] = "pandarenracial_innerpeace",
    ["perdicion"] = "ability_creature_cursed_03",
    ["pericia"] = "ability_rogue_stayofexecution",
    ["pico"] = "inv_misc_birdbeck_01",
    ["piedad con los moribundos"] = "ability_pvp_defenderoftheweak",
    ["piel demoniaca"] = "spell_shadow_ragingscream",
    ["plegaria de curacion"] = "eps_bg3_prayerofhealing",
    ["poder runico"] = "spell_shadow_rune",
    ["poder totemico corriente purificadora"] = "inv_spear_04",
    ["poder totemico marea viva"] = "spell_nature_riptide",
    ["poder totemico resistencia elemental"] = "ability_shaman_multitotemactivation",
    ["posicion de privilegio"] = "eps_wc3h_evilhumanqueen",
    ["potenciar protecciones"] = "ability_demonhunter_empowerwards",
    ["presencia retorcida"] = "achievement_explore_argus",
    ["prestidigitacion"] = "spell_arcane_arcanepotency",
    ["proteccion contra el bien y el mal"] = "eps_bg3_heavilyarmored",
    ["proteccion mental"] = "hd_ldaknowledge",
    ["protocolo de emergencia"] = "inv_misc_enggizmos_27",
    ["purificar comida y bebida"] = "inv_misc_food_100",
    ["racha de calor"] = "ability_ironmaidens_grapeshotblast",
    ["rapidez feral"] = "ability_druid_dash",
    ["renacer oscuro"] = "eps_wc3_deathknight",
    ["reparar"] = "ability_repair",
    ["reprension infernal"] = "ability_warlock_inferno",
    ["reserva de furia"] = "ability_warrior_focusedrage",
    ["reserva de ira"] = "ability_warrior_focusedrage",
    ["resiliencia vil"] = "eps_wc3h_felwither",
    ["resistencia"] = "eps_bg3_resistance",
    ["restablecimiento menor"] = "spell_holy_renew",
    ["reversion de conjuros"] = "eps_bg3_counterspell",
    ["salto"] = "eps_bg3_longjump",
    ["salto de pie"] = "eps_bg3_jump",
    ["secretos profanos"] = "spell_warlock_demonbolt",
    ["segundo aliento"] = "ability_hunter_harass",
    ["sentido divino"] = "spell_holy_heroism",
    ["sentido magico"] = "spell_holy_magicalsentry",
    ["sentidos agudos"] = "eps_wc3_nightelfcharm",
    ["sirviente invisible"] = "w3reforgedinvisibility",
    ["susurro de plantas"] = "ability_druid_nourish",
    ["taumaturgia"] = "ability_mage_incantersabsorbtion",
    ["tocar a los muertos"] = "eps_bg3_howlofdead",
    ["toque de vida"] = "ability_warlock_mortalcoil",
    ["toque helado"] = "spell_deathknight_icetouch",
    ["tormenta divina"] = "ability_paladin_divinestorm",
    ["totemista"] = "ability_shaman_totemrelocation",
    ["vacio oscuro"] = "hots_velkoz_voidrift",
    ["veredicto del templario"] = "spell_paladin_templarsverdict",
    ["vida entre sombras"] = "spell_rogue_shadow_reflection",
    ["vil"] = "eps_wc3h_felpact",
    ["vision en la oscuridad"] = "eps_bg3_darkvision",
    ["vision en la oscuridad superior"] = "eps_bg3_darkvision",
    ["vision espectral"] = "ability_demonhunter_eyebeam",
    ["vista aguda"] = "ability_druid_healinginstincts",
    ["vista de penumbra"] = "eps_bg3_darkvision",
    ["voz psiquica"] = "inv_hivemind",
    ["zancada prodigiosa"] = "eps_bg3_dash",
}

-- Presentacion verificada contra las tarjetas de rasgo de perfiles TRP3 de GRIKER.
-- Es datos estaticos del addon: nunca se lee un SavedVariable de TRP3 durante juego.
Catalog.presentationNames = {
    ["artes marciales"] = "ability_monk_deadlyreach",
    ["ataque adicional"] = "eps_bg3_multiattack",
    ["bastion divino"] = "spell_holy_divineshield",
    ["chi"] = "ability_monk_chicocoon",
    ["control de ira"] = "spell_nature_shamanrage",
    ["dedos de escarcha"] = "eps_lol_ashe_frostshot2",
    ["enfoque"] = "ability_hunter_focusfire",
    ["entrenamiento de centinela"] = "eps_wc3h_ceremoniallocketelune",
    ["estilo de combate"] = "ability_hunter_snipertraining",
    ["formulas de trucos"] = "inv_glyph_minormage",
    ["fragmentos de alma"] = "inv_misc_gem_amethyst_02",
    ["furia de elune"] = "eps_wc3_darkelune",
    ["gracia de elune"] = "spell_holy_elunesgrace",
    ["metamagia"] = "ability_monk_counteractmagic",
    ["palma aturdidora"] = "ability_monk_paralysis",
    ["palma de chi ji"] = "ability_monk_cranekick",
    ["provocacion"] = "spell_nature_reincarnation",
    ["rejuvenecimiento"] = "spell_nature_rejuvenation",
    ["rodar"] = "ability_monk_roll",
    ["serenidad"] = "ability_monk_serenity",
    ["canalizar divinidad"] = "spell_holy_lightsgrace",
    ["conjuros del sacerdocio de elune"] = "spell_nature_starfall",
    ["accion astuta"] = "ability_rogue_fleetfooted",
    ["alacridad"] = "rogue_burstofspeed",
    ["armas runicas"] = "spell_deathknight_frozenruneweapon",
    ["ataque furtivo"] = "ability_rogue_bladetwisting",
    ["cambio de forma"] = "ability_druid_tigersroar",
    ["canalizar fuego demoniaco"] = "hd_create_emberfel",
    ["constitucion no muerta"] = "inv_qirajidol_death",
    ["defensa sin armadura"] = "inv_leather_raiddemonhunter_q_02helm",
    ["disparo arcano"] = "ability_impalingbolt",
    ["domar bestia"] = "ability_hunter_beasttaming",
    ["druidico"] = "ability_druid_lunarguidance",
    ["empatia animal"] = "ability_hunter_pet_assist",
    ["espiral de la muerte"] = "spell_shadow_deathcoil",
    ["explorador natural"] = "ability_hunter_pathfinding2",
    ["fuente de magia"] = "spell_shadow_manafeed",
    ["golpe de escarcha"] = "spell_deathknight_empowerruneblade2",
    ["golpe del cruzado"] = "inv_sword_08",
    ["golpe runico"] = "achievement_dungeon_icecrown_frostmourne",
    ["guia ancestral"] = "ability_shaman_ancestralguidance",
    ["imposicion de manos"] = "spell_holy_layonhands",
    ["iniciacion illidari"] = "ability_demonhunter_eyeofleotheras",
    ["llamas del caos"] = "spell_fire_felfire",
    ["lobo solitario: ataque apuntado"] = "ability_hunter_steadyshot",
    ["maquina de matar"] = "inv_sword_122",
    ["marca del cazador"] = "ability_hunter_markedfordeath",
    ["metamorfosis"] = "ability_demonhunter_metamorphasisdps",
    ["misivas secretas"] = "archaeology_5_0_changkiboard",
    ["mordida de demonio"] = "ability_demonhunter_torment",
    ["pericia"] = "ability_rogue_stayofexecution",
    ["piromaniaco"] = "ability_warlock_backdraft",
    ["poder runico"] = "spell_shadow_rune",
    ["racha de calor"] = "ability_ironmaidens_grapeshotblast",
    ["renacer oscuro"] = "eps_wc3_deathknight",
    ["secretos profanos"] = "spell_warlock_demonbolt",
    ["segundo aliento"] = "ability_hunter_harass",
    ["sentido divino"] = "spell_holy_heroism",
    ["sentido magico"] = "spell_holy_magicalsentry",
    ["toque de vida"] = "ability_warlock_mortalcoil",
    ["totemista"] = "ability_shaman_totemrelocation",
    ["vil"] = "eps_wc3h_felpact",
    ["vision espectral"] = "ability_demonhunter_eyebeam",
    ["accion astuta"] = "ability_rogue_fleetfooted",
    ["adaptacion salvaje"] = "eps_wow_wildstalkr",
    ["afinidad elemental"] = "ability_shawaterelemental_reform",
    ["afinidades salvajes"] = "ability_druid_earthandsky",
    ["alacridad"] = "rogue_burstofspeed",
    ["armas runicas"] = "spell_deathknight_frozenruneweapon",
    ["arrollar"] = "ability_warrior_challange",
    ["artes marciales"] = "ability_monk_deadlyreach",
    ["ataque adicional"] = "eps_bg3_multiattack",
    ["ataque furtivo"] = "ability_rogue_bladetwisting",
    ["bastion divino"] = "spell_holy_divineshield",
    ["cambio de forma"] = "ability_druid_tigersroar",
    ["canalizar divinidad"] = "spell_holy_lightsgrace",
    ["canalizar fuego demoniaco"] = "hd_create_emberfel",
    ["carga"] = "ability_warrior_charge",
    ["chi"] = "ability_monk_chicocoon",
    ["conocimiento demoniaco"] = "warlock_sacrificial_pact",
    ["constitucion no muerta"] = "inv_qirajidol_death",
    ["control de ira"] = "spell_nature_shamanrage",
    ["dedos de escarcha"] = "eps_lol_ashe_frostshot2",
    ["defensa sin armadura"] = "ability_monk_shuffle",
    ["desarme"] = "ability_warrior_disarm",
    ["disparo arcano"] = "ability_impalingbolt",
    ["domar bestia"] = "ability_hunter_beasttaming",
    ["druidico"] = "ability_druid_lunarguidance",
    ["ecos de fe"] = "hots_anduin_holywordsalvation",
    ["empatia animal"] = "ability_hunter_pet_assist",
    ["energia"] = "ability_rogue_vigor",
    ["enfoque"] = "ability_hunter_focusfire",
    ["entrenamiento de centinela"] = "eps_wc3h_ceremoniallocketelune",
    ["escudo de sangre"] = "artifactability_blooddeathknight_umbilicuseternus",
    ["espiral de la muerte"] = "spell_shadow_deathcoil",
    ["explorador natural"] = "ability_hunter_pathfinding2",
    ["exponer armadura"] = "ability_rogue_dismantle",
    ["formulas de trucos"] = "inv_glyph_minormage",
    ["fragmentos de alma"] = "inv_misc_gem_amethyst_02",
    ["fuente de magia"] = "spell_shadow_manafeed",
    ["furia"] = "ability_warrior_innerrage",
    ["furia de elune"] = "eps_wc3_darkelune",
    ["garrote"] = "ability_rogue_garrote",
    ["golpe de escarcha"] = "spell_deathknight_empowerruneblade2",
    ["golpe del cruzado"] = "inv_sword_08",
    ["golpe heroico"] = "ability_warrior_punishingblow",
    ["golpe runico"] = "achievement_dungeon_icecrown_frostmourne",
    ["gracia de elune"] = "spell_holy_elunesgrace",
    ["guia ancestral"] = "ability_shaman_ancestralguidance",
    ["himno divino"] = "ability_priest_heavanlyvoice",
    ["imposicion de manos"] = "spell_holy_layonhands",
    ["iniciacion illidari"] = "ability_demonhunter_eyeofleotheras",
    ["intrepido"] = "ability_warrior_revenge",
    ["ira"] = "ability_warrior_innerrage",
    ["kalimag"] = "eps_lol_taliyah_unraveledearth",
    ["legado del vacio"] = "hots_malzahar_voidshift",
    ["llamas del caos"] = "spell_fire_felfire",
    ["lobo solitario: ataque apuntado"] = "ability_hunter_steadyshot",
    ["maquina de matar"] = "inv_sword_122",
    ["marca del cazador"] = "ability_hunter_markedfordeath",
    ["metamagia"] = "ability_monk_counteractmagic",
    ["metamorfosis"] = "ability_demonhunter_metamorphasisdps",
    ["misivas secretas"] = "archaeology_5_0_changkiboard",
    ["momentum"] = "ability_demonhunter_doublejump",
    ["mordida de demonio"] = "ability_demonhunter_torment",
    ["mutilar"] = "ability_rogue_shadowstrikes",
    ["palma aturdidora"] = "ability_monk_paralysis",
    ["palma de chi ji"] = "ability_monk_cranekick",
    ["pericia"] = "ability_rogue_stayofexecution",
    ["piromaniaco"] = "ability_warlock_backdraft",
    ["poder runico"] = "spell_shadow_rune",
    ["provocacion"] = "spell_nature_reincarnation",
    ["racha de calor"] = "ability_ironmaidens_grapeshotblast",
    ["rejuvenecimiento"] = "spell_nature_rejuvenation",
    ["renacer oscuro"] = "eps_wc3_deathknight",
    ["rodar"] = "ability_monk_roll",
    ["secretos profanos"] = "spell_warlock_demonbolt",
    ["segundo aliento"] = "ability_hunter_harass",
    ["sentido divino"] = "spell_holy_heroism",
    ["sentido magico"] = "spell_holy_magicalsentry",
    ["serenidad"] = "ability_monk_serenity",
    ["toque de vida"] = "ability_warlock_mortalcoil",
    ["tormenta divina"] = "ability_paladin_divinestorm",
    ["totemista"] = "ability_shaman_totemrelocation",
    ["vil"] = "eps_wc3h_felpact",
    ["vision espectral"] = "ability_demonhunter_spectralsight",
    ["vista de penumbra"] = "eps_bg3_darkvision",
    ["voz psiquica"] = "inv_hivemind",
}
for name, icon in pairs(Catalog.presentationNames) do
    if not Catalog.names[name] then Catalog.names[name] = icon end
end

Catalog.features = {
    bg_hered_superv = "inv_scroll_11",
    bg_org_perspicacia = "inv_scroll_11",
    animador = "eps_bg3_playlute",
    acolito_luz_abisal = "ability_priest_innerlightandshadow",
    adepto_cosecha_oscura = "ability_warlock_infernogreen",
    agente_principe_mercante = "eps_hs_grimygoblin",
    animador_gladiador = "achievement_featsofstrength_gladiator_03",
    aprendiz_kirin_tor = "achievement_kirintor_offensive",
    artesano_gremial_comerciante_gremial = "eps_arc_sign_oribos_trade",
    bucanero_retirado = "eps_plunder_armor_bloodsailbuccaneer_01_helm",
    caballero_orden = "eps_lol_tft_knightemblem",
    charlatan = "achievement_halloween_smiley_01",
    crianza_faccion = "hd_hordeflag_blue",
    criminal = "ability_rogue_masterofsubtlety",
    criminal_espia = "inv_misc_spyglass_01",
    cruzado_argenta = "eps_wc3h_argentshield",
    doble_agente = "factionchange",
    eremita = "inv_misc_tabard_lorewalkers",
    ermitano = "spell_nature_naturetouchdecay",
    exiliado_alterac = "achievement_zone_alteracmountains_01",
    feriante_luna_negra = "poster_darkmoon1",
    forastero = "achievement_bg_dg_master_of_the_deepwind_gorge",
    forjador_torio = "ability_racial_massproduction",
    guardia_ciudad_detective = "Secret",
    heredero = "inv_icon_heirloomtoken_weapon02",
    heroe_pueblo = "achievement_guild_forgreatjusticerank2",
    marinero = "ships_ability_boardingpartyalliance",
    marinero_pirata = "inv_helm_cloth_b_01pirate_classic",
    mercenario_veterano_harford_veterano_harford = "inv_tabard_duelersguild",
    miembro_anillo_tierra = "inv_misc_tabard_earthenring",
    miembro_organizacion = "achievement_guildperk_everybodysfriend",
    miembro_tribal = "spell_fire_totemofwrath",
    noble_caballero_nobiliario = "wc3_knight",
    novato_liga_expedicionarios = "INV_Cape_Armor_Explorer_D_01_backpack",
    operativo_ravenholdt = "Medivh_RavenForm",
    protector_cenarion = "achievement_reputation_guardiansofcenarius",
    salvaje = "ability_hunter_beastwithin",
    soldado = "w3reforgedfootman",
    superviviente_catastrofe = "achievement_zone_cataclysm",
    acechador = "ability_druid_prowl",
    actor = "eps_lol_profileicon_songofnunubraum",
    adepto_metamagia = "spell_holy_dispelmagic",
    adepto_sobrenatural = "ability_ardenweald_warlock",
    afortunado = "inv_misc_herb_goldclover",
    agilidad_robusta = "ability_rogue_fleetfooted",
    alerta = "inv_misc_bell_01",
    apresador = "ability_warrior_titansgrip",
    artillero_dote = "inv_misc_ammo_bullet_02",
    atacante_carga = "ability_warrior_charge",
    atacante_salvaje = "warrior_wild_strike",
    atleta = "eps_bg3_sprint",
    azote_magos = "ability_demonhunter_consumemagic",
    centinela = "ability_warrior_revenge",
    cocinero = "achievement_profession_chefhat",
    combatiente_dos_armas = "ability_dualwield",
    combatiente_montado = "w3reforgedknight",
    cortador = "ability_revendreth_rogue",
    depredador_endurecido = "ability_racial_darkflight",
    duelista_defensivo = "ability_parry",
    duro = "ability_warrior_intensifyrage",
    envenenador = "trade_brewpoison",
    experto_ballestas = "inv_weapon_crossbow_09",
    experto_habilidades = "ability_mage_studentofthemind",
    explorador_mazmorras = "inv_enchanting_70_pet_torch",
    feat_ar_agarre = "inv_scroll_11",
    feat_ar_competencia = "inv_scroll_11",
    feat_ar_velocidad = "ability_rogue_sprint",
    feat_av_reroll = "spell_necro_deathrift",
    feat_de_correr = "ability_racial_runningwild",
    feat_de_garras = "ability_racial_flayer",
    feat_de_mordisco = "inv_misc_monsterfang_02",
    feat_eaf_cercania = "spell_misc_hellifrepvpcombatmorale",
    feat_fo_dado = "ability_warrior_deepcuts",
    feat_fo_reaccion = "ability_warrior_warcry",
    feat_ge_conjuro = "spell_nature_healingwavelesser",
    feat_ge_miedo = "eps_lol_profileicon_runespirit2",
    feat_gma_potente = "ability_rogue_sabreslash",
    feat_mesc_defensa = "inv_shield_05",
    feat_mesc_embate = "ability_warrior_shieldbash",
    feat_phb_acechador = "inv_scroll_11",
    feat_phb_afortunado = "inv_misc_herb_goldclover_leaf",
    feat_phb_alerta_ini = "ability_rogue_fleetfooted",
    feat_phb_resiliente = "inv_scroll_11",
    feat_rf_conocimiento = "d3_berserkerrage",
    feat_rf_enemigos = "eps_lol_gnar_ragegene",
    feat_rf_oportunidad = "d3_battlerage",
    feat_rt_pg = "eps_wc3h_taurenanger",
    feat_rt_piel = "inv_misc_nativebeastskin",
    feat_tco_artif_tool = "inv_scroll_11",
    furia_orca = "spell_winston_rage",
    guia_espiritual = "eps_lol_profileicon_runespirit",
    habilidoso = "ability_kaztik_dominatemind",
    iniciado_artificiero = "eps_lol_profileicon_elementofmagma",
    iniciado_combate = "ability_rogue_combatreadiness",
    iniciado_magia = "spell_mage_presenceofmind",
    lanzador_combate = "ability_mage_burnout",
    lanzador_preciso = "eps_lol_profileicon_truedamage",
    lanzador_ritual = "hots_mageprofile",
    lider_inspirador = "achievement_guildperk_everyones a hero",
    ligeramente_acorazado = "inv_chest_chain_03",
    linguista = "trade_archaeology_silverscrollcase",
    maestro_armaduras_medias = "inv_chest_chain_05",
    maestro_armaduras_pesadas = "inv_chest_plate02",
    maestro_armas = "garrison_weaponupgrade",
    maestro_armas_asta = "inv_spear_05",
    maestro_armas_pesadas = "inv_sword_111",
    maestro_escudero = "ability_warrior_shieldguard",
    maestro_escudos = "inv_shield_06",
    maton_taberna = "ability_racial_brushitoff",
    mente_aguda = "dos2_mind",
    moderadamente_acorazado = "inv_armor_shoulder_plate_naxxramas_raidwarrior_c_01",
    movil = "ability_rogue_fleetfooted",
    muy_acorazado = "eps_wc3h_platedhelmet",
    observador = "WH_EagleEye",
    perforador = "ability_warrior_shieldbreak",
    prodigio = "w3reforgedhumanarcanetower",
    rencor_faccion = "eps_lol_tryndamere_undyingrage",
    resiliente = "HotS_ResilientShield",
    resistencia_tauren = "eps_wc3_tauren",
    resistente = "ability_warrior_strengthofarms",
    sanador = "eps_rumble_traithealer",
    tau_tau_atleta = "achievement_zone_dragonblight_03",
    tau_tau_frio = "eps_wc3_frostarmornogore",
    telepata = "spell_arcane_mindmastery",
    telequinetico = "WH_FocusedMind",
    tirador_primera = "ability_marksmanship",
    tocado_hadas = "eps_bg3_feyprotectiongreen",
    tocado_sombras = "spell_shadow_shadowembrace",
    triturador = "ability_smash",
    tro_zan_armas = "inv_polearm_2h_zandalariguard_b_01",
    versado_armas = "ability_warrior_weaponmastery",
    versado_elemento = "LiMing_TalRashasElements",
    cha_mej_ataques_3 = "spell_shaman_unleashweapon_wind",
    cha_mej_llamado_marcial = "spell_shaman_spewlava",
    pal_pro_consagracion = "spell_holy_innerfire",
    pal_sagrado_conjuros_3 = "spell_holy_aspiration",
    cdm_profana_conjuros_3 = "ability_deathknight_deathsiphon2",
    cdm_profana_conjuros_5 = "ability_deathknight_deathsiphon2",
    cha_ele_vinculo_agua_3 = "inv_elemental_mote_water01",
    cha_ele_vinculo_agua_5 = "inv_elemental_mote_water01",
    cha_ele_vinculo_aire_3 = "inv_elemental_mote_air01",
    cha_ele_vinculo_aire_5 = "inv_elemental_mote_air01",
    cha_ele_vinculo_fuego_3 = "inv_elemental_mote_fire01",
    cha_ele_vinculo_fuego_5 = "inv_elemental_mote_fire01",
    cha_ele_vinculo_tierra_3 = "inv_elemental_mote_earth01",
    cha_ele_vinculo_tierra_5 = "inv_elemental_mote_earth01",
    cha_mej_golpe_elemental = "spell_shaman_improvedstormstrike",
    pal_pro_escudo_sagrado = "spell_holy_blessingofprotection",
    pal_ret_rechazar = "ability_paladin_turnevil",
    pal_ret_veredicto = "spell_paladin_templarsverdict",
    cha_totem_aire = "spell_nature_invisibilitytotem",
    cha_totem_fuego = "spell_nature_guardianward",
    cha_totem_tierra = "spell_nature_earthbindtotem",
    monje_cer_buey_negro = "ability_monk_chibrew",
    pal_sag_luz_amanecer = "ability_paladin_blindinglight2",
    pal_sag_martillo_luz = "ability_paladin_judgementofthepure",
    caz_enf_ataque_preciso = "eps_lol_ashe_focus",
    caz_enf_llamada = "ability_hunter_huntervswild",
    cha_totem_agua = "inv_spear_04",
    cha_totem_resistencia = "ability_shaman_multitotemactivation",
    disciplina_expiacion = "ability_priest_atonement",
    feat_de_olfato = "eps_wc3_enchantedbear",
    feat_gma_adicional = "eps_bg3_multiattack",
    feat_pr_pericia = "ability_rogue_stayofexecution",
    feat_tco_exph_exp = "ability_rogue_stayofexecution",
    gran_maestro_armas = "ability_warrior_unrelentingassault",
    monje_chi_danza = "ability_monk_uplift",
    monje_chi_efusion = "ability_monk_vivify",
    monje_chi_paso = "ability_monk_ridethewind",
    monje_chi_punos = "monk_ability_fistoffury",
    bru_forja_alma = "inv_misc_orb_04",
    bru_forja_conjuro = "inv_misc_gem_sapphire_01",
    bru_forja_fuego = "inv_ammo_firetar",
    bru_forja_salud = "inv_stone_04",
    bru_nucleo_diablillo = "spell_shadow_summonimp",
    bru_nucleo_guardia_vil = "spell_shadow_summonfelguard",
    bru_nucleo_manafago = "spell_shadow_summonfelhunter",
    bru_nucleo_sucubo = "spell_shadow_summonsuccubus",
    caz_enf_tacticas = "ability_hunter_huntingparty",
    tau_tau_tundra = "wh_walkbetweenworlds",
    tro_bos_armas = "eps_wc3h_trollishaxe",
    tro_hie_armas = "eps_wc3h_trollishaxe",
    abrazo_vacio = "Malzahar_VoidShift",
    adepto_armas_fuego = "w3reforgedflaregun",
    amigo_criaturas = "Ivern_FriendOfTheForest",
    elv_frio = "ability_racial_chillofnight",
    elv_grieta = "ability_racial_spatialrift",
    experto_armas_fuego = "inv_legendary_gun",
    feat_ac_animales = "eps_bg3_speakwithanimals",
    feat_ac_conjuros = "ability_druid_mastershapeshifter",
    feat_adf_armas = "inv_weapon_rifle_04",
    feat_adf_armero = "inv_misc_profession_book_engineering",
    feat_av_aura = "inv_enchant_voidsphere",
    feat_eaf_extra = "ability_hunter_rapidregeneration",
    feat_eaf_recarga = "ability_hunter_lockandload",
    feat_fe_esquivar = "XinZhao_Determination",
    feat_hd_espiritu = "ability_racial_ultravision",
    feat_hd_sigilo = "ability_racial_shadowmeld",
    feat_mae_armas = "inv_sword_109",
    feat_mb_cercania = "spell_misc_hellifrepvpcombatmorale",
    feat_mb_potente = "ArcaneIntensity",
    feat_mb_trucos = "spell_mage_arcaneorb",
    feat_mq_alquimista = "inv_misc_5potionbag_special",
    feat_mq_mejora = "eps_hs_bloodfurypotion",
    feat_mq_pocion = "eps_bg3_identify",
    feat_pe_reroll = "Tyrande_HuntersMark",
    feat_ta_conjuro = "eps_lol_shen_shadowdashold",
    fortaleza_enana = "WH_DeadlyDetermination",
    gob_esquivar = "ability_racial_timeismoney",
    gob_familiaridad = "inv_eng_gizmo3",
    gob_ingenieria = "inv_gizmo_rocketlauncher",
    gob_tratos = "achievement_guildperk_bartering",
    herencia_darnassiana = "eps_wc3_nightelfflag",
    maestro_armas_exoticas = "inv_legendary_sword",
    mago_de_batalla = "inv_shoulders_cloth_raidmage_s_01",
    mejor_quimica = "ability_racial_betterlivingthroughchemistry",
    noc_magia = "icon_7fx_nightborn_astromancer_blue",
    noc_solar = "sha_ability_rogue_envelopingshadows_nightborne",
    orc_caz_emboscador = "ability_rogue_ambush",
    orc_caz_sorpresa = "eps_lol_rk_pyke_ambush",
    orc_gue_agresivo = "ability_racial_bloodrage",
    orc_gue_salvajes = "warrior_talent_icon_furyintheblood",
    orc_mis_conocimientos = "ability_racial_ancienthistory",
    orc_mis_llamado = "ability_racial_ancestralcall",
    pan_palma = "pandarenracial_quiveringpain",
    precision_elfica = "ability_hunter_aimedshot",
    ren_hum_versatilidad = "ability_rogue_versatility",
    tau_armas = "inv_archaeology_70_tauren_handsmoothedpyrestone",
    tau_construccion = "eps_wc3h_taurenwardrum",
    tau_cuernos = "inv_misc_horn_05",
    tau_ma_montanes = "ability_racial_mountaineer",
    tau_ma_tenacidad = "ability_racial_bullrush",
    tau_mul_pisoton = "ability_warstomp",
    teletransporte_arcano = "spell_arcane_arcanepotency_nightborne",
    tro_bos_instintos = "hots_zuljin_amanirage",
    tro_hie_constitucion = "w3reforgedicetrollshaman",
    tro_hie_piel = "spell_frost_coldhearted",
    tro_jun_armas = "eps_wc3h_trollishaxe",
    tro_jun_berserker = "racial_troll_berserk",
    tro_jun_voodoo = "eps_wc3h_voodoohelm",
    tro_regeneracion = "ability_racial_regeneratin",
    tro_zan_loa = "ability_racial_embraceoftheloa_gonk",
    hum_versatilidad = "inv_misc_book_08",
    ena_entrenamiento = "achievement_zone_ironforge",
    ena_piedra = "trade_archaeology_dwarf_runestone",
    ena_forjaz_dureza = "ability_toughness",
    ena_forjaz_piedra = "spell_shadow_unholystrength",
    ["ena_mart_altura"] = "trade_archaeology_carved wildhammer gryphon figurine",
    ena_mart_valentia = "dos2_warrior7",
    ena_mart_domador = "ability_druid_naturalperfection",
    ena_hn_sangre = "ability_racial_fireblood",
    ena_hn_forjado = "ability_racial_foregedinflames",
    eln_armas = "inv_sword_1h_warfrontsnightelf_d_01",
    sme_arcano = "ability_racial_arcaneaffinity",
    ren_elf_arcano = "ability_racial_arcaneaffinity",
    noc_arcano = "ability_racial_arcaneaffinity",
    dra_sombras = "ability_priest_halo_shadow",
    dra_exo_gemas = "inv_jewelcrafting_argusgemcut_purple_miscicons",
    dra_fl_forjado = "spell_holy_auramastery",
    dra_fl_resistencia = "ability_racial_holyresistance",
    dra_fl_juicio = "ability_paladin_toweroflight",
    dra_tab_elemental = "spell_nature_elementalprecision_1",
    dra_tab_paria = "eps_wc3_brokendraenei",
    hua_cazador = "hd_book2motif_gilneas",
    orc_amenazante = "ability_warrior_furiousresolve",
    orc_armas = "inv_archaeology_orcclans_warsongpike",
    orc_resistencia = "ability_warrior_bloodsurge",
    -- Trampas comparte dibujo con el lanzatrampas a proposito: es el icono real del
    -- rasgo y no hay otro que lo diga igual de claro.
    supervivencia_trampas = "ability_hunter_traplauncher",
    restauracion_corteza_de_hierro = "spell_nature_stoneclawtotem",
    bestias_vinculo_del_companero = "ability_hunter_pet_assist",
    cervecero_brebaje_fortificante = "ability_monk_fortifyingale_new",
    cervecero_brebaje_de_piel_de_hierro = "inv_drink_05",
    cervecero_te_de_trueno = "ability_monk_thunderfocustea",
    afliccion_maldiciones = "spell_shadow_antishadow",
    guerrero_maniobras_3 = "ability_warrior_weaponmastery",
    guerrero_maniobras_6 = "ability_warrior_trauma",
    -- Rasgos raciales: el id evita que nombres compartidos como
    -- "Conocimiento Arcano" hereden el icono de otra raza o clase.
    esa_arcano = "ability_racial_arcaneaffinity",
    cdm_comando_oscuro = "spell_deathknight_strangulate", cdm_portador_plagas = "spell_deathknight_plaguestrike",
    cdm_presencia_maligna = "spell_deathknight_unholypresence", cdm_ataque_extra = "ability_warrior_savageblow",
    -- Tarjetas TRP3 de Magia base por clase. No son iconos de rasgos: cada
    -- entrada corresponde al campo IC de "Magia <Clase>".
    cdm_forja_runas = "spell_deathknight_frozenruneweapon", cdm_lanzamiento_conjuros = "hots_malthael_death_shroud",
    dh_dev_competencia = "ability_demonhunter_doublejump", dh_dev_embestida = "ability_demonhunter_infernalimpact",
    dh_dev_momentum_vengativo = "ability_demonhunter_chaosstrike", dh_ven_competencia = "ability_demonhunter_torment",
    dh_ven_tormento = "ability_demonhunter_torment", dh_ven_puas = "ability_demonhunter_immolationaura",
    dh_ira_competencia = "ability_demonhunter_eyebeam", dh_ira_marca_ignea = "ability_demonhunter_immolationaura",
    dh_defensa_sin_armadura = "inv_leather_raiddemonhunter_q_02helm", dh_marca_demoniaca = "ability_demonhunter_markedfordeath",
    dh_hambre_instintiva = "ability_demonhunter_consumemagic", dru_eq_conjuros_camino = "spell_nature_starfall",
    dru_eq_invocar = "spell_nature_natureblessing", dru_eq_fuerza_naturaleza = "ability_druid_forceofnature",
    dru_fer_marca_ursol = "ability_druid_maul", dru_fer_afinidad = "ability_druid_primaltenacity",
    dru_fer_instintos = "ability_druid_healinginstincts", dru_fer_ataque_adicional = "eps_bg3_multiattack",
    dru_fer_tacticas = "ability_druid_catform", dru_res_conjuros_camino = "spell_nature_healingtouch",
    dru_res_marca_salvaje = "spell_nature_regeneration", dru_lanzamiento_conjuros = "ability_druid_manatree",
    dru_senda = "ability_druid_lunarguidance", dru_mejora_cambio_forma = "ability_druid_tigersroar",
    caz_bes_domador = "ability_hunter_beasttaming", caz_bes_aspecto = "ability_hunter_aspectmastery",
    caz_bes_comando = "ability_hunter_pet_assist", caz_pun_disparo_conmocionante = "spell_frost_stun",
    caz_pun_lobo_ataque = "eps_bg3_multiattack", caz_sup_trampero = "ability_hunter_traplauncher",
    -- Verificados contra la ficha TRP3 de Maxwell: Supervivencia (Cazador 3).
    caz_sup_estudiante = "ability_hunter_onewithnature", caz_sup_lobo_salvaje = "spell_hunter_lonewolf",
    caz_sup_corte_ala = "ability_rogue_trip", caz_sup_lobo_ataque = "eps_bg3_multiattack",
    caz_arquetipo = "ability_hunter_snipertraining", mago_arc_truco = "spell_arcane_arcanepotency",
    mago_arc_cargas = "spell_arcane_arcane01", mago_arc_desplazamiento = "spell_arcane_teleportstormwind",
    mago_arc_brillantez = "spell_arcane_blast", mago_fue_truco = "inv_elemental_mote_fire01",
    mago_fue_cauterizar = "spell_fire_fire", mago_esc_truco = "spell_frost_frostbolt02",
    mago_esc_congelacion = "spell_frost_frostarmor", mago_lanzamiento_conjuros = "eps_rumble_arcaneblastpose",
    mago_estudio_magico = "spell_holy_magicalsentry", monje_cer_competencia = "ability_monk_brewmaster",
    monje_cer_brebajes = "ability_monk_brewmaster", monje_cer_tambaleo = "ability_monk_stagger",
    monje_tej_niebla_calmante = "ability_monk_soothingmists", monje_tej_caminante = "ability_monk_roll",
    monje_cam_golpes_lanza = "ability_monk_paralysis", monje_cam_reflejos = "ability_monk_tigerslust",
    monje_cam_caminavientos = "ability_monk_windwalker_spec", monje_tradicion = "ability_monk_wayofthecrane",
    monje_golpes_empoderados_chi = "ability_monk_jab", pal_sag_canalizar = "spell_holy_lightsgrace",
    pal_sag_destello = "spell_holy_flashheal", pal_pro_canalizar = "spell_holy_lightsgrace",
    pal_ret_canalizar = "spell_holy_lightsgrace", pal_lanzamiento_conjuros = "ability_paladin_blessedmending",
    pal_camino_sagrado = "spell_holy_devotionaura", pal_ataque_extra = "eps_bg3_multiattack",
    pal_aura_proteccion = "spell_holy_devotionaura", sac_dis_truco = "spell_holy_holysmite",
    sac_dis_supresion = "spell_holy_painsuppression", sac_sag_competencia = "spell_holy_mindsooth",
    sac_sag_oracion = "spell_holy_prayerofhealing", sac_som_forma = "spell_shadow_shadowform",
    -- Tarjetas TRP3 de Magia: base Sacerdotisa y especializacion Elune.
    sac_lanzamiento_conjuros = "ability_priest_focusedwill", sac_elu_conjuros = "eps_lol_diana_moonsilverblade",
    sac_encadenar_no_muertos = "spell_nature_slow", sac_palabra_poder = "spell_holy_prayerofmendingtga",
    sac_restauracion_fieles = "spell_holy_heal",
    pic_ase_competencia = "ability_rogue_deadenednerves", pic_ase_intuicion = "ability_rogue_findweakness",
    pic_for_competencia = "ability_rogue_pistolshot", pic_arquetipo = "ability_rogue_masterofsubtlety",
    pic_esquiva_sobrenatural = "ability_rogue_feint", pic_pericia_2 = "ability_rogue_stayofexecution",
    cha_ele_poder = "spell_nature_tremortotem", cha_ele_furia = "spell_nature_callstorm",
    cha_ele_eco = "ability_shaman_echooftheelements", cha_mej_poder = "spell_nature_windfury",
    cha_mej_competencia = "inv_axe_1h_steelwarrior", cha_mej_torbellino = "ability_whirlwind",
    cha_mej_ataque_adicional = "eps_bg3_multiattack", cha_res_poder = "spell_nature_riptide",
    cha_res_fuerzas = "spell_nature_groundingtotem", cha_lanzamiento_conjuros = "ability_shaman_ascendance",
    cha_vinculo = "spell_shaman_astralshift", cha_bestia_espiritual = "spell_shaman_feralspirit",
    bru_afl_lista = "spell_shadow_curse", bru_afl_corrupcion = "spell_shadow_abominationexplosion",
    bru_afl_acechar = "spell_shadow_twilight", bru_afl_maestro_maldiciones = "spell_shadow_curseofmannoroth",
    bru_dem_lista = "spell_shadow_summonfelhunter", bru_dem_conducto = "spell_shadow_soulleech",
    bru_dem_sentir = "spell_shadow_mindrot", bru_dem_vinculo_almas = "spell_shadow_soulleech",
    bru_des_lista = "spell_shadow_rainoffire", bru_des_caos = "spell_fire_fireball",
    bru_hechiceria_vil = "ability_warlock_everlastingaffliction", bru_estudio_vil = "spell_warlock_demonbolt",
    bru_secretos_profanos = "spell_warlock_demonbolt", bru_toque_vida = "ability_warlock_mortalcoil",
    bru_conocimiento_demoniaco = "warlock_sacrificial_pact", bru_grimorio_sacrificio = "warlock_grimoireofsacrifice",
    bru_nucleo_abisario = "spell_shadow_summonvoidwalker", bru_fragmentos_alma = "inv_misc_gem_amethyst_02",
    bru_capturar_fragmento = "inv_misc_gem_amethyst_02", bru_circulo_demoniaco = "spell_shadow_demoniccircleteleport",
    bru_quemar_alma_extender = "ability_warlock_coil2", bru_quemar_alma_acelerar = "warlock_spelldrain",
    bru_quemar_alma_rebotar = "spell_priest_shadoworbs", bru_ritos_alma = "spell_warlock_soulburn",
    bru_forjado_almas = "inv_misc_gem_amethyst_02", gue_fur_desatada = "ability_warrior_innerrage",
    gue_fur_temible = "ability_warrior_intensifyrage", guerrero_furia_interna = "ability_warrior_innerrage",
    guerrero_arquetipo_marcial = "ability_warrior_savageblow", guerrero_ataque_extra = "eps_bg3_multiattack",
    guerrero_accion_adicional = "ability_warrior_offensivestance",
}
Catalog.spells = {
    agarre_electrizante = { "eps_bg3_shockingrasp" },
    burla_danina = { "eps_bg3_cuttingwords" },
    crear_llama = { "eps_bg3_produceflame" },
    descarga_de_fuego = { "spell_fire_firebolt02" },
    descarga_de_relampago = { "spell_nature_lightning" },
    descarga_sobrenatural = { "hots_alarak_lightningsurge" },
    descomponer = { "spell_deathknight_necroticplague" },
    deslizamiento_sombrio = { "eps_lol_shen_shadowdashold" },
    diabolismo = { "spell_shadow_demonictactics" },
    explosion_arcana = { "spell_nature_wispsplode" },
    explosion_lunar = { "eps_lol_aurelionsol_fallingstar" },
    explosion_mental = { "spell_shadow_unholyfrenzy" },
    garrote_shillelagh = { "eps_bg3_shilleigh" },
    golpe_lunar = { "spell_nature_moonglow" },
    guia = { "eps_bg3_combatguidance" },
    ilusion_menor = { "eps_bg3_tosscoin" },
    impacto_certero = { "eps_lol_rk_pyke_marktarget" },
    invocar_elementos = { "ability_shaman_ascendance" },
    ira_solar = { "ability_skyreach_solar_burst" },
    llama_sagrada = { "eps_bg3_sacredflameholy" },
    llama_vil = { "spell_fire_felfire" },
    luces_danzantes = { "eps_bg3_dancinglights" },
    luz = { "eps_bg3_lightholy" },
    mano_de_mago = { "eps_bg3_magehand" },
    mensaje = { "d3_focusedmind" },
    piedad_con_los_moribundos = { "eps_bg3_preservelife" },
    prestidigitacion = { "ability_mage_incantersabsorbtion" },
    rafaga = { "smite_merlin_ice_a01" },
    rayo_de_escarcha = { "ability_mage_rayoffrost" },
    rayo_sombrio = { "ability_ironmaidens_convulsiveshadows" },
    reparar = { "eps_bg3_repair" },
    resistencia = { "spell_holy_wordfortitude" },
    rociada_venenosa = { "eps_bg3_poisonspray" },
    saber_druidico = { "eps_bg3_knowledgeowl" },
    salpicadura_acida = { "ability_creature_poison_06" },
    sp_castigo_abrasador = { "ability_paladin_bladeofjustice" },
    sp_resplandor_enfermizo = { "ability_malkorok_blightofyshaarj_green" },
    taumaturgia = { "ability_priest_bindingprayers" },
    toque_del_caos = { "ability_warlock_chaosbolt" },
    toque_helado = { "spell_deathknight_icetouch" },
    amigos = { "eps_bg3_friends", "Interface\\Icons\\Spell_Holy_MindVision" },
    controlar_llamas = { "eps_lol_profileicon_deathfiretouchmastery2016" },
    crear_fogata = { "inv_summerfest_firedrink" },
    guardia_con_hoja = { "eps_bg3_bladebarrier" },
    hoja_retumbante = { "spell_shaman_primalstrike" },
    hoja_verdeante = { "inv_knife_1h_felfireraid_d_04" },
    latigo_de_espinas = { "eps_bg3_thornwhip" },
    llamada_de_la_muerte = { "inv_misc_bell_green" },
    llamada_de_relampago = { "eps_bg3_calllightning" },
    moldear_agua = { "eps_lol_item_staffofflowingwater" },
    moldear_tierra = { "inv_misc_volatileearth" },
    mordedura_helada = { "ability_mage_frostjaw" },
    palabra_de_radiancia = { "eps_bg3_divinestrikeattack" },
    picadura_absorbente = { "spell_shadow_contagion" },
    resguardo_de_hoja = { "ability_warrior_shieldreflection" },
    retumbo = { "eps_lol_leesin_sonicwaveold" },
    salvajismo_primitivo = { "warwick_jawsofthebeast" },
    codificar_pensamientos = { "dos2_mind" },
    alarma = { "inv_misc_bell_01" },
    armadura_de_mago = { "spell_magearmor" },
    bendicion = { "eps_bg3_bless" },
    buenas_bayas = { "inv_misc_food_40" },
    caida_de_pluma = { "spell_magic_featherfall" },
    crear_o_destruir_agua = { "hots_thebutcher_freshmeat_water" },
    curar_heridas = { "eps_bg3_curewounds" },
    detectar_el_bien_y_el_mal = { "eps_bg3_detectevilandgood" },
    detectar_magia = { "spell_mage_presenceofmind" },
    detectar_venenos_y_enfermedades = { "Interface\\Icons\\Spell_Fire_FireBolt02", "eps_buildershaven_gobinfo" },
    disco_flotante_de_tenser = { "ability_mount_cloudmount" },
    disfrazarse = { "ability_rogue_disguise" },
    dormir = { "spell_nature_sleep" },
    encantar_animal = { "eps_bg3_animalfriends" },
    encontrar_familiar = { "eps_bg3_rangercompanion" },
    enmaranar = { "eps_lol_zyra_graspingroot", "Interface\\Icons\\Spell_Nature_StrangleVines" },
    entender_idiomas = { "eps_bg3_comprehendlanguages" },
    escudo = { "eps_bg3_spellshield" },
    escudo_de_fe = { "eps_bg3_shieldoffaith" },
    falsa_vida = { "eps_bg3_falselife" },
    favor_divino = { "eps_bg3_divinefavorholy" },
    fuego_feerico = { "spell_nature_faeriefire" },
    grasa = { "inv_pig" },
    hablar_con_los_animales = { "eps_bg3_speakwithanimals" },
    hechizar_persona = { "eps_bg3_charmperson" },
    heroismo = { "eps_bg3_heroism" },
    identificar = { "eps_bg3_identify" },
    imagen_silenciosa = { "d3_mirrorimage" },
    infligir_heridas = { "eps_bg3_inflictwounds" },
    manos_ardientes = { "spell_fire_soulburn" },
    marca_del_cazador = { "ability_hunter_snipershot" },
    nube_de_oscurecimiento = { "eps_lol_vex_loomingdarkness" },
    ola_atronadora = { "eps_bg3_thunderwave" },
    orden_imperiosa = { "ability_warrior_rallyingcry" },
    palabra_de_curacion = { "eps_bg3_healingword" },
    perdicion = { "eps_bg3_bane" },
    proteccion_contra_el_bien_y_el_mal = { "eps_bg3_heavilyarmored" },
    proyectil_magico = { "eps_bg3_magicmissile" },
    purificar_comida_y_bebida = { "hd_create_food" },
    reprension_infernal = { "hd_curseofelements_fire" },
    retirada_expeditiva = { "eps_bg3_retreat" },
    risa_horrible_de_tasha = { "eps_bg3_tashaslaughter" },
    rociada_de_color = { "hd_fellowshippotions_colormixredorange" },
    saeta_guiada = { "eps_bg3_guidingboltholy" },
    salto = { "eps_bg3_longjump" },
    santuario = { "eps_bg3_sanctuary" },
    sirviente_invisible = { "spell_shadow_impphaseshift" },
    texto_ilusorio = { "inv_misc_profession_book_inscription" },
    zancada_prodigiosa = { "eps_bg3_longstrider" },
    abrir = { "eps_rumble_picklock" },
    absorber_elementos = { "spell_nature_elementalabsorption" },
    armadura_de_agathys = { "ability_deathknight_remorselesswinters2" },
    aumentar_gravedad = { "hots_kaelthas_gravitylapse_blue" },
    brazos_de_hadar = { "d3_shadowpower" },
    brebaje_caustico_de_tasha = { "ability_deathwing_grasping_tendrilsgreen" },
    causar_miedo = { "spell_shadow_possession" },
    ceremonia = { "spell_holy_testoffaith" },
    cuchillo_de_hielo = { "eps_bg3_iceknife" },
    dedos_de_escarcha = { "eps_lol_ashe_frostshot2" },
    detectar_veneno_y_enfermedad = { "d3_focusedmind_gold" },
    don_de_la_alacridad = { "eps_bg3_haste" },
    encantar_persona = { "spell_shadow_shadowworddominate" },
    enredar = { "eps_wc3_entanglingroots" },
    golpe_ardiente = { "spell_shaman_improvelavalash" },
    golpe_furioso = { "wh_furyofasuryan", "eps_bg3_divinesmite" },
    golpe_llameante = { "ability_paladin_divinestorm" },
    golpe_trueno = { "spell_shaman_focusedstrikes" },
    orbe_cromatico = { "spell_frostfire orb" },
    pies_ligeros = { "spell_lifegivingspeed" },
    rayo_de_bruja = { "spell_nature_chainlightning" },
    rayo_de_enfermedad = { "eps_bg3_rayofsickness" },
    replica_infernal = { "spell:80240", "eps_bg3_fireballfel", "eps_buildershaven_gobinfo" },
    temblor_de_tierra = { "spell_shaman_earthquake" },
    trampa = { "eps_lol_kled_traponarope" },
    vida_falsa = { "spell:20707", "eps_bg3_aid", "eps_buildershaven_gobinfo" },
    vinculo_de_bestia = { "ability_hunter_pet_assist" },
    duelo_obligado = { "ability_warrior_challange" },
    maldicion = { "ability_creature_cursed_03" },
    susurros_disonantes = { "eps_lol_sona_songofcelerityold" },
    agarre_de_la_muerte = { "spell_deathknight_strangulate" },
    arrepentimiento = { "spell_holy_prayerofhealing" },
    cadenas_de_hielo = { "spell_frost_chainsofice" },
    choque_elemental = { "spell_nature_elementalprecision_1" },
    drenar_vida = { "spell_shadow_lifedrain02" },
    escudo_de_relampagos = { "spell_nature_lightningshield" },
    explosion_de_cadaveres = { "ability_creature_disease_02" },
    favor_aterrador = { "ability_revendreth_deathknight" },
    fuego_estelar = { "spell_arcane_starfire" },
    fuego_interior = { "spell_holy_innerfire" },
    piel_demoniaca = { "spell_shadow_ragingscream" },
    pluma_angelica = { "ability_priest_angelicfeather" },
    proyectil_de_fuego_y_hielo = { "ability_mage_frostfirebolt" },
    toque_helado_nivel_1 = { "dos2_ghost13" },
    vacio_oscuro = { "inv_elemental_primal_shadow" },
    vision_mental = { "spell_holy_mindvision" },
    agrandar_reducir = { "eps_hs_pintsizepotion" },
    alterar_el_propio_aspecto = { "eps_lol_tft_shapeshifteremblem" },
    arma_espiritual = { "eps_bg3_magicweapon" },
    arma_magica = { "eps_bg3_blessweapon" },
    augurio = { "spell_monk_zenpilgrimage" },
    aura_magica_de_nystul = { "wh_corruptingretribution", "spell_holy_magicalsentry" },
    auxilio = { "wh_heartoffire", "eps_bg3_nightsongaidblue" },
    boca_magica = { "inv_relics_runestone" },
    calentar_metal = { "eps_bg3_heatmetal" },
    calmar_emociones = { "spell_arcane_focusedpower" },
    castigo_marcador = { "spell_holy_sealofwrath" },
    cerradura_arcana = { "eps_bg3_arcanelock" },
    contorno_borroso = { "d3_blur" },
    crecimiento_espinoso = { "eps_bg3_spikegrowth" },
    detectar_pensamientos = { "eps_bg3_detectthoughts" },
    detectar_trampas = { "ability_spy" },
    dulce_descanso = { "warrior_talent_icon_deadlycalm" },
    embelesar = { "spell_holy_silence" },
    esfera_de_llamas = { "inv_misc_orb_05" },
    flecha_acida_de_melf = { "spell_hunter_exoticmunitions_poisoned" },
    hacer_anicos = { "eps_lol_orianna_commandshockwave" },
    hallar_corcel = { "spell_nature_swiftness" },
    hoja_de_fuego = { "eps_lol_gangplank_trialbyfire", "Interface\\Icons\\Spell_Fire_FlameTounge" },
    imagen_multiple = { "ability_mage_massinvisibility" },
    inmovilizar_persona = { "spell_mage_overpowered" },
    invisibilidad = { "ability_mage_invisibility" },
    levitar = { "eps_bg3_levitate", "Interface\\Icons\\Spell_Holy_LayOnHands" },
    llama_permanente = { "eps_bg3_sacredflameelune" },
    localizar_animales_o_plantas = { "ability_druid_healinginstincts" },
    localizar_objeto = { "w3reforgedpickupitem" },
    mensajero_animal = { "eps_bg3_catattention" },
    oscuridad = { "spell_shadow_auraofdarkness" },
    pasar_sin_rastro = { "eps_bg3_cloakshadows" },
    paso_brumoso = { "eps_bg3_mistystep" },
    piel_robliza = { "spell_nature_skinofearth" },
    plegaria_de_curacion = { "eps_bg3_prayerofhealing" },
    potenciar_caracteristica = { "spell_magic_greaterblessingofkings" },
    proteccion_contra_veneno = { "hots_thebutcher_freshmeat_poison" },
    rafaga_de_viento = { "eps_bg3_gustofwind" },
    rayo_abrasador = { "eps_bg3_scorchingray" },
    rayo_de_luna = { "eps_bg3_moonbeam" },
    rayo_debilitador = { "warlock_curse_weakness" },
    restablecimiento_menor = { "spell_holy_purify" },
    silencio = { "eps_bg3_silence" },
    sordera_ceguera = { "spell_shadow_painandsuffering" },
    sugestion = { "spell_shadow_charm" },
    telarana = { "eps_bg3_conjureweb" },
    trepar_cual_aracnido = { "achievement_halloween_spider_01" },
    truco_de_la_cuerda = { "inv_misc_rope_01" },
    ver_invisibilidad = { "spell_shadow_detectinvisibility" },
    vinculo_protector = { "eps_bg3_wardingbond" },
    vision_en_la_oscuridad = { "eps_bg3_darkvision" },
    zona_de_verdad = { "smite_aurelionsol_celestialexpansion" },
    bomba_viva = { "ability_blackhand_attachedslagbombs" },
    cascara_antimagica = { "spell_shadow_antimagicshell" },
    ciclon = { "w3reforgedcyclone" },
    crear_piedra_de_salud = { "hd_create_healstone" },
    desgarrar_mente = { "eps_lol_zilean_mindtwist" },
    desvanecerse = { "spell_magic_lesserinvisibilty" },
    encadenar_no_muertos = { "ability_deathknight_deathchain" },
    enfoque_interior = { "w3reforgedinnerfire" },
    erupcion_de_lava = { "spell_shaman_lavaburst" },
    exorcismo = { "spell_holy_excorcism_02" },
    explosion_aullante = { "spell_frost_arcticwinds" },
    fortaleza_de_hielo = { "spell_deathknight_iceboundfortitude" },
    fuerza_brillante = { "eps_bg3_beaconofhope" },
    golpe_justo = { "spell_holy_crusaderstrike" },
    guardian_del_rey = { "spell_paladin_clarityofpurpose" },
    hervor_de_sangre = { "spell_deathknight_bloodboil" },
    prisma_sagrado = { "spell_paladin_holyprism" },
    toque_helado_nivel_2 = { "ability_deathknight_icygrip" },
    voluntad_interior = { "hots_cassia_innerlight" },
    acelerar = { "ability_socererking_arcaneacceleration" },
    animar_a_los_muertos = { "inv_pet_ghoul" },
    bola_de_fuego = { "spell_fire_fireball02" },
    caminar_sobre_el_agua = { "spell_frost_windwalkon" },
    circulo_magico = { "spell_arcane_blast" },
    clarividencia = { "hd_ldaeye" },
    conjurar_animales = { "spell_druid_wildcharge" },
    contrahechizo = { "eps_bg3_counterspell" },
    corcel_fantasma = { "inv_mount_spectralhorse" },
    crear_comida_y_agua = { "hd_create_conjurabletable" },
    crecimiento_vegetal = { "eps_bg3_plantgrowth" },
    desplazamiento = { "spell:1953", "eps_buildershaven_gobinfo" },
    disipar_magia = { "spell_holy_dispelmagic" },
    don_de_lenguas = { "smite_kumbhakarna_a03" },
    espiritus_guardianes = { "eps_bg3_spiritguardians" },
    forma_gaseosa = { "inv_misc_volatileair" },
    fundirse_con_la_piedra = { "spell_shadow_unholystrength" },
    glifo_custodio = { "inv_misc_rune_03" },
    hablar_con_las_plantas = { "ability_druid_serenefocus" },
    hablar_con_los_muertos = { "eps_bg3_speakwithdead" },
    imagen_mayor = { "spell_arcane_arcanetactics" },
    imponer_maldicion = { "ability_creature_cursed_04" },
    indetectable = { "w3reforgedinvisibility" },
    levantar_maldicion = { "w3reforgedcurse" },
    llamar_al_relampago = { "eps_bg3_lightningblast" },
    luz_del_dia = { "eps_bg3_daylight" },
    muro_de_viento = { "eps_lol_rk_yasuo_windwall" },
    nube_apestosa = { "w3reforgedplaguecloud" },
    palabra_de_curacion_en_masa = { "eps_bg3_masshealingword" },
    patron_hipnotico = { "eps_bg3_hypnogaze" },
    pequena_choza_de_leomund = { "eps_lol_blitzcrank_manabarrier" },
    proteccion_contra_energia = { "inv_shield_1h_artifactstormfist_d_06" },
    ralentizar = { "d3_slowtime" },
    recado = { "ability_mage_studentofthemind" },
    relampago = { "eps_bg3_lightningbolt" },
    respirar_bajo_el_agua = { "spell_shadow_demonbreath" },
    revivir = { "eps_bg3_revivfy" },
    senal_de_esperanza = { "ability_priest_rayofhope" },
    terror = { "hd_warlock_fear" },
    toque_vampirico = { "spell_shadow_improvedvampiricembrace" },
    tormenta_de_aguanieve = { "spell_frost_ice shards" },
    volar = { "eps_bg3_fly" },
    asfixiar = { "ability_deathknight_asphixiate" },
    cadena_de_curacion = { "spell_nature_healingwavegreater" },
    cambio_de_vacio = { "spell_priest_voidshift" },
    estrella_divina = { "spell_priest_divinestar" },
    explosion_arcana_nivel_3 = { "ability_monk_forcesphere_pink" },
    faro_de_luz = { "ability_paladin_beaconoflight" },
    horror_psiquico = { "spell_shadow_psychichorrors" },
    ira_sagrada = { "ability_paladin_sanctifiedwrath" },
    luz_cegadora = { "ability_paladin_blindinglight2" },
    manto_del_cruzado_caido = { "spell_holy_retributionaura" },
    nova_sagrada = { "spell_holy_holynova" },
    oleada_estelar = { "spell_arcane_arcane03" },
    pua_terrestre = { "ability_earthen_pillar" },
    robar_conjuro = { "spell_arcane_arcane02" },
    ventisca = { "d3_blizzard" },
    adivinacion = { "spell_nature_crystalball" },
    ampliar_o_disminuir_magia = { "spell_arcane_studentofmagic" },
    apariciones_sombrias = { "spell_shadow_shadesofdarkness" },
    asesino_fantasmal = { "hd_warlock_fearscream" },
    aura_de_pureza = { "wh_purify", "spell_holy_devotionaura" },
    aura_de_vida = { "spell_holy_auramastery" },
    barrera_luminosa = { "eps_lol_spell_barriernew" },
    bloque_de_hielo = { "spell_frost_frost" },
    cofre_secreto_de_leomund = { "eps_lol_rk_missfortune_fortunesfavor", "Interface\\Icons\\INV_Box_01" },
    compulsion = { "ability_hunter_killcommand" },
    confusion = { "d3_massconfusion" },
    conjurar_criaturas_del_bosque = { "eps_rumble_faeriedragon" },
    conjurar_elementales_menores = { "inv_pet_pandarenelemental" },
    conjurar_no_muertos = { "w3reforgedabomination" },
    controlar_agua = { "eps_lol_rk_illaoi_crashingtides" },
    descarga_arcana = { "spell_arcane_arcane01" },
    destierro = { "spell_shadow_cripple" },
    dominar_bestia = { "eps_bg3_dominatebeast" },
    dominar_no_muertos = { "inv_misc_bone_skull_01" },
    encantar_monstruo = { "hots_sylvanas_mindcontrol" },
    encontrar_corcel_mayor = { "ability_mount_dreadsteed" },
    escudo_de_fuego = { "dos2_fireshield" },
    escudo_divino = { "spell_holy_divineshield" },
    esfera_de_agua = { "spell_animaardenweald_orb" },
    esfera_de_tormenta = { "spell_broker_orb" },
    esfera_resiliente_de_otiluke = { "ability_racial_forceshield" },
    esfera_vitriolica = { "eps_arc_orbgreen" },
    fuego_y_azufre = { "ability_warlock_fireandbrimstone" },
    golpe_devastador = { "ability_warrior_savageblow" },
    guardian_de_la_fe = { "eps_bg3_guardianoffaith" },
    guardian_de_la_naturaleza = { "eps_wc3h_aquaticdruid" },
    invisibilidad_mayor = { "ability_mage_greaterinvisibility" },
    invocar_aberracion = { "ability_socererking_summonaberration" },
    invocar_demonio_mayor = { "ability_warlock_demonicpower" },
    invocar_elemental = { "spell_fire_elemental_totem" },
    invocar_entidad_del_vacio = { "inv_nzothfish_void" },
    lanza_psiquica_de_raulothim = { "eps_lol_pantheon_spearshot" },
    libertad_de_movimiento = { "rogue_burstofspeed" },
    localizar_criatura = { "inv_misc_map02" },
    marchitar = { "inv_misc_herb_12" },
    mensajero_rapido_de_galder = { "achievement_guildperk_gmail" },
    moldear_piedra = { "inv_stone_sharpeningstone_01" },
    muerte_y_decadencia = { "w3reforgeddeathanddecay" },
    muro_de_fuego = { "eps_bg3_walloffire" },
    ojo_arcano = { "eps_bg3_arcaneeye" },
    parra_atrapante = { "w3reforgedentanglingroots" },
    perdicion_elemental = { "hd_curseofelements_greenred" },
    piel_de_piedra = { "w3reforgedresistantskin" },
    plaga_devoradora = { "spell_shadow_devouringplague" },
    polimorfia = { "ability_mage_improvedpolymorph" },
    proteccion_contra_la_muerte = { "spell_holy_guardianspirit" },
    puerta_dimensional = { "inv_artifact_dimensionalrift" },
    radiancia_enferma = { "spell_animamaldraxxus_orb" },
    sabueso_de_mordenkainen = { "inv_pet_mastiff" },
    santuario_privado_de_mordenkainen = { "spell_arcane_teleportdalaran" },
    sombra_de_moil = { "spell_shadow_shadowform" },
    sumidero_gravitacional = { "hots_kaelthas_gravitylapse_purple" },
    tentaculos_negros_de_evard = { "spell_shadow_shadowfury" },
    terreno_ilusorio = { "achievement_zone_arathihighlands_01" },
    tormenta_de_hielo = { "w3reforgedblizzard" },
    vortice_de_ursol = { "spell_druid_ursolsvortex" },
    aguijon_mental = { "spell_priest_mindspike" },
    aliento_de_dragon = { "inv_misc_head_dragon_01" },
    bolsillo_de_muneca = { "inv_misc_coinbag06" },
    corona_de_locura = { "inv_helmet_01" },
    diablo_de_polvo = { "inv_misc_dust" },
    don_de_la_charla = { "achievement_halloween_smiley_01" },
    escritura_celeste = { "inv_fabric_celestial_cloth" },
    espiritu_curativo = { "shaman_pvp_ripplingwaters" },
    favor_de_la_fortuna = { "inv_misc_fortunecookie" },
    flechas_igneas = { "ability_searingarrow" },
    fuerza_fantasmal = { "spell_shaman_ancestralawakening" },
    hoja_sombria = { "inv_knife_1h_grimbatolraid_d_03" },
    latigo_mental_de_tasha = { "ability_warlock_whiplash" },
    llama_de_aganazzar = { "eps_lol_brand_pillarofflame" },
    nube_de_dagas = { "eps_bg3_cloudofdaggers" },
    objeto_inamovible = { "inv_stone_weightstone_02" },
    paso_sombrio = { "ability_rogue_shadowstep" },
    pirotecnia = { "spell_frost_fireresistancetotem" },
    puno_terrestre_de_maximiliano = { "misc_drogbartotem02" },
    rebano_de_familiares = { "w3reforgedflyingsheep" },
    sentido_de_bestia = { "eps_wc3h_direwolfacutesenses" },
    tormenta_de_bolas_de_nieve_de_snilloc = { "eps_lol_nunu_snowballbarrage" },
    viento_guardian = { "wh_windsprotection", "ability_druid_cyclone" },
    amigos_rapidos = { "achievement_guildperk_everybodysfriend" },
    arma_elemental = { "inv_weapon_shortblade_98" },
    aura_de_vitalidad = { "eps_bg3_auraofvitality" },
    discurso_motivador = { "eps_lol_spell_rally" },
    enemigos_en_abundancia = { "d3_fetisharmy" },
    fingir_muerte = { "ability_rogue_feigndeath" },
    fortaleza_intelectual = { "wh_focusedmind", "spell_holy_arcaneintellect" },
    golpe_cegador = { "ability_paladin_blindinglight" },
    hambre_de_hadar = { "eps_bg3_hungerofhadar" },
    invocar_demonios_menores = { "ability_warlock_empoweredimp" },
    invocar_no_muertos = { "spell_shadow_darksummoning" },
    invocar_sombras = { "spell_shadow_summonvoidwalker" },
    manto_del_cruzado = { "spell_holy_crusade" },
    meteoros_menores_de_melf = { "spell_fire_meteorstorm" },
    muro_de_agua = { "eps_bg3_wallofice" },
    ola_de_marea = { "eps_lol_nami_tidalwave" },
    onda_de_pulso = { "eps_lol_leesin_sonicwave" },
    parpadeo = { "wc3_blink" },
    paso_de_trueno = { "ability_thunderking_overcharge" },
    sirviente_minusculo = { "eps_rumble_npcstonegolem" },
    sueno_profundo = { "smite_kumbhakarna_passive" },
    tierra_en_erupcion = { "w3reforgedvolcano" },
    torre_de_galder = { "w3reforgedguardtower" },
    transferencia_de_vida = { "spell_shadow_lifedrain" },
}

-- Icono de los CONJUROS de cada especializacion, sacado del frame "Magia <X>"
-- de los perfiles TRP3. Es distinto del icono de la especializacion, que sale
-- del frame "Especializacion <X>" y ya vive en Catalog.subclasses.
Catalog.subclassSpells = {
    ["brujo/destruccion"] = "ability_warlock_burningembers",
    ["caballero_muerte/escarcha"] = "ability_deathknight_heartstopaura",
    ["caballero_muerte/sangre"] = "ability_deathwing_bloodcorruption_death",
    ["druida/restauracion"] = "spell_nature_resistnature",
    ["mago/fuego"] = "eps_lol_rk_ahri_vastayanflames",
    ["paladin/proteccion"] = "ability_paladin_shieldofthetemplar",
    ["paladin/represion"] = "ability_paladin_empoweredsealsjustice",
    ["picaro/sutileza"] = "ability_rogue_shadowstep",
    ["sacerdote/disciplina"] = "spell_holy_powerwordshield",
    ["sacerdote/elune"] = "eps_lol_diana_moonsilverblade",
    ["sacerdote/sagrado"] = "spell_priest_chakra",
    ["sacerdote/sombra"] = "spell_priest_divinestar_shadow",
}

Catalog.subclasses = {
    caballero_muerte = { sangre = "spell_deathknight_bloodpresence", escarcha = "spell_deathknight_frostpresence", profana = "spell_deathknight_unholypresence" },
    cazador_demonios = { ira = "ability_demonhunter_chaoticimprint_fire", devastacion = "ability_demonhunter_specdps", venganza = "ability_demonhunter_spectank" },
    druida = { feral = "ability_druid_catform", restauracion = "spell_nature_healingtouch", equilibrio = "spell_nature_starfall" },
    cazador = { punteria = "ability_hunter_focusedaim", supervivencia = "ability_hunter_camouflage", bestias = "ability_hunter_bestialdiscipline" },
    mago = { fuego = "spell_fire_flamebolt", arcano = "spell_holy_magicalsentry", escarcha = "spell_frost_frostbolt02" },
    monje = { tejedor = "spell_monk_mistweaver_spec", cervecero = "spell_monk_brewmaster_spec", caminavientos = "spell_monk_windwalker_spec" },
    paladin = { sagrado = "spell_holy_holybolt", proteccion = "spell_holy_devotionaura", represion = "spell_holy_auraoflight" },
    sacerdote = { disciplina = "spell_holy_wordfortitude", sagrado = "spell_holy_guardianspirit", sombra = "spell_shadow_shadowwordpain", elune = "eps_wc3h_nightelfpriestessofthemoon1" },
    picaro = { asesino = "ability_rogue_eviscerate", forajido = "ability_rogue_waylay", sutileza = "ability_stealth" },
    chaman = { restauracion = "spell_nature_healingwavegreater", elemental = "spell_nature_lightning", mejora = "spell_shaman_improvedstormstrike" },
    brujo = { destruccion = "spell_shadow_rainoffire", afliccion = "spell_shadow_deathcoil", demonologia = "spell_shadow_metamorphosis" },
    guerrero = { armas = "ability_warrior_savageblow", proteccion = "ability_warrior_defensivestance", furia = "ability_warrior_innerrage" },
}

-- Rasgos que no aparecen en los perfiles de referencia actuales. Se mantienen
-- por id estable para que nombres repetidos (p.ej. "Ataque Adicional") no
-- compartan accidentalmente la presentacion de otra clase.

local function TexturePath(icon)
    if not icon or icon == "" then return nil end
    if type(icon) == "number" then return icon end
    if type(icon) ~= "string" then return nil end
    if icon:sub(1, 10) == "Interface\\" then return icon end
    return "Interface\\Icons\\" .. icon
end

function Catalog.RegisterFeatures(entries)
    for id, icon in pairs(entries or {}) do
        Catalog.features[tostring(id)] = icon
    end
end

function Catalog.RegisterFeatureIfMissing(featureId, icon)
    local id = tostring(featureId or "")
    if id == "" or Catalog.features[id] then return end
    Catalog.features[id] = icon
end

function Catalog.RegisterSpells(entries)
    for id, candidates in pairs(entries or {}) do
        Catalog.spells[tostring(id)] = candidates
    end
end

function Catalog.RegisterSubclasses(entries)
    for classId, subclasses in pairs(entries or {}) do
        Catalog.subclasses[tostring(classId)] = subclasses
    end
end

function Catalog.GetFeatureIcon(featureId)
    return TexturePath(Catalog.features[tostring(featureId or "")])
end

function Catalog.GetSpellCandidates(spellId)
    return Catalog.spells[tostring(spellId or "")]
end

function Catalog.GetSubclassIcon(classId, subclassId)
    local subclasses = Catalog.subclasses[tostring(classId or "")]
    return TexturePath(subclasses and subclasses[tostring(subclassId or "")])
end
