local API = _G.HarfordCompendioAPI
if not API then return end
local IconCatalog = _G.HarfordIconCatalog

local PENDING_ICON_NAME = "eps_buildershaven_gobinfo"

-- Candidatos de icono POR NOMBRE para cada conjuro, en orden de preferencia (arte BG3/eps
-- primero, respaldo del cliente despues; "spell:<id>" resuelve via GetSpellTexture). Esta tabla
-- vivia aqui y SE PERDIO en el refactor de carpetas (918a636): la version nueva delegaba en
-- IconCatalog.GetSpellCandidates pero NADIE llamaba a RegisterSpells, asi que los candidatos
-- quedaron vacios -- el Compendio perdia el arte preferente y el generador del About de TRP3,
-- sin nombre que usar, escribia el fileID numerico en {icon:...}, que TRP3 no sabe renderizar
-- (antepone Interface\ICONS\ al texto). Recuperada del git y registrada en el catalogo.
local BG3_ICON_CANDIDATES_BY_SPELL_ID = {
    agarre_electrizante = { "eps_bg3_shockingrasp" },
    burla_danina = { "eps_bg3_cuttingwords" },
    crear_llama = { "eps_bg3_produceflame" },
    descarga_de_fuego = { "spell_fire_firebolt02" },
    descarga_de_relampago = { "spell_nature_lightning" },
    descarga_sobrenatural = { "hots_alarak_lightningsurge" },
    descomponer = { "spell_deathknight_necroticplague" },
    deslizamiento_sombrio = { "eps_lol_shen_shadowdashold" },
    diabolismo = { "spell_shadow_demonictactics" },
    explosion_arcana = { "spell_nature_wispsplode" },
    explosion_mental = { "spell_shadow_unholyfrenzy" },
    garrote_shillelagh = { "eps_bg3_shilleigh" },
    golpe_lunar = { "spell_nature_moonglow" },
    guia = { "eps_bg3_combatguidance" },
    ilusion_menor = { "eps_bg3_tosscoin" },
    impacto_certero = { "eps_lol_rk_pyke_marktarget" },
    invocar_elementos = { "ability_shaman_ascendance" },
    ira_solar = { "ability_skyreach_solar_burst" },
    llama_sagrada = { "eps_bg3_sacredflameholy" },
    llama_vil = { "spell_fire_felfire" },
    luces_danzantes = { "eps_bg3_dancinglights" },
    luz = { "eps_bg3_lightholy" },
    mano_de_mago = { "eps_bg3_magehand" },
    mensaje = { "d3_focusedmind" },
    piedad_con_los_moribundos = { "eps_bg3_preservelife" },
    prestidigitacion = { "ability_mage_incantersabsorbtion" },
    rafaga = { "smite_merlin_ice_a01" },
    rayo_de_escarcha = { "ability_mage_rayoffrost" },
    rayo_sombrio = { "ability_ironmaidens_convulsiveshadows" },
    reparar = { "eps_bg3_repair" },
    resistencia = { "spell_holy_wordfortitude" },
    rociada_venenosa = { "eps_bg3_poisonspray" },
    saber_druidico = { "eps_bg3_knowledgeowl" },
    salpicadura_acida = { "ability_creature_poison_06" },
    taumaturgia = { "ability_priest_bindingprayers" },
    toque_del_caos = { "ability_warlock_chaosbolt" },
    toque_helado = { "spell_deathknight_icetouch" },
    amigos = { "eps_bg3_fiends", "eps_bg3_friends", "Interface\\Icons\\Spell_Holy_MindVision" },
    controlar_llamas = { "eps_lol_profileicon_deathfiretouchmastery2016" },
    crear_fogata = { "inv_summerfest_firedrink" },
    guardia_con_hoja = { "eps_bg3_bladebarrier" },
    hoja_retumbante = { "spell_shaman_primalstrike" },
    hoja_verdeante = { "inv_knife_1h_felfireraid_d_04" },
    latigo_de_espinas = { "eps_bg3_thornwhip" },
    llamada_de_la_muerte = { "inv_misc_bell_green" },
    llamada_de_relampago = { "eps_bg3_calllightning" },
    moldear_agua = { "eps_lol_item_staffofflowingwater" },
    moldear_tierra = { "inv_misc_volatileearth" },
    mordedura_helada = { "ability_mage_frostjaw" },
    palabra_de_radiancia = { "eps_bg3_divinestrikeattack" },
    picadura_absorbente = { "spell_shadow_contagion" },
    resguardo_de_hoja = { "ability_warrior_shieldreflection" },
    retumbo = { "eps_lol_leesin_sonicwaveold" },
    salvajismo_primitivo = { "warwick_jawsofthebeast" },
    codificar_pensamientos = { "dos2_mind" },
    alarma = { "inv_misc_bell_01" },
    armadura_de_mago = { "spell_magearmor" },
    bendicion = { "eps_bg3_bless" },
    buenas_bayas = { "inv_misc_food_40" },
    caida_de_pluma = { "spell_magic_featherfall" },
    crear_o_destruir_agua = { "hots_thebutcher_freshmeat_water" },
    curar_heridas = { "eps_bg3_curewounds" },
    detectar_el_bien_y_el_mal = { "eps_bg3_detectevilandgood" },
    detectar_magia = { "spell_mage_presenceofmind" },
    detectar_venenos_y_enfermedades = { "Interface\\Icons\\Spell_Fire_FireBolt02", "eps_buildershaven_gobinfo" },
    disco_flotante_de_tenser = { "ability_mount_cloudmount" },
    disfrazarse = { "ability_rogue_disguise" },
    dormir = { "spell_nature_sleep" },
    encantar_animal = { "eps_bg3_animalfriends" },
    encontrar_familiar = { "eps_bg3_rangercompanion" },
    enmaranar = { "eps_lol_zyra_graspingroot", "Interface\\Icons\\Spell_Nature_StrangleVines", "w3reforgedentanglingroots" },
    entender_idiomas = { "eps_bg3_comprehendlanguages" },
    escudo = { "eps_bg3_spellshield" },
    escudo_de_fe = { "eps_bg3_shieldoffaith" },
    falsa_vida = { "eps_bg3_falselife" },
    favor_divino = { "eps_bg3_divinefavorholy" },
    fuego_feerico = { "spell_nature_faeriefire" },
    grasa = { "inv_pig" },
    hablar_con_los_animales = { "eps_bg3_speakwithanimals" },
    hechizar_persona = { "eps_bg3_charmperson" },
    heroismo = { "eps_bg3_heroism" },
    identificar = { "eps_bg3_identify" },
    imagen_silenciosa = { "d3_mirrorimage" },
    infligir_heridas = { "eps_bg3_inflictwounds" },
    manos_ardientes = { "spell_fire_soulburn" },
    marca_del_cazador = { "ability_hunter_snipershot" },
    nube_de_oscurecimiento = { "eps_lol_vex_loomingdarkness" },
    ola_atronadora = { "eps_bg3_thunderwave" },
    orden_imperiosa = { "ability_warrior_rallyingcry" },
    palabra_de_curacion = { "eps_bg3_healingword" },
    perdicion = { "eps_bg3_bane" },
    proteccion_contra_el_bien_y_el_mal = { "eps_bg3_heavilyarmored" },
    proyectil_magico = { "eps_bg3_magicmissile" },
    purificar_comida_y_bebida = { "hd_create_food" },
    reprension_infernal = { "hd_curseofelements_fire", "ability_warlock_inferno" },
    retirada_expeditiva = { "eps_bg3_retreat" },
    risa_horrible_de_tasha = { "eps_bg3_tashaslaughter" },
    rociada_de_color = { "hd_fellowshippotions_colormixredorange" },
    saeta_guiada = { "eps_bg3_guidingboltholy" },
    salto = { "eps_bg3_longjump" },
    santuario = { "eps_bg3_sanctuary" },
    sirviente_invisible = { "spell_shadow_impphaseshift" },
    texto_ilusorio = { "inv_misc_profession_book_inscription" },
    zancada_prodigiosa = { "eps_bg3_longstrider" },
    abrir = { "eps_rumble_picklock" },
    absorber_elementos = { "spell_nature_elementalabsorption" },
    armadura_de_agathys = { "ability_deathknight_remorselesswinters2" },
    aumentar_gravedad = { "hots_kaelthas_gravitylapse_blue" },
    brazos_de_hadar = { "d3_shadowpower" },
    brebaje_caustico_de_tasha = { "ability_deathwing_grasping_tendrilsgreen" },
    causar_miedo = { "spell_shadow_possession" },
    ceremonia = { "spell_holy_testoffaith" },
    cuchillo_de_hielo = { "eps_bg3_iceknife" },
    dedos_de_escarcha = { "eps_lol_ashe_frostshot2" },
    detectar_veneno_y_enfermedad = { "d3_focusedmind_gold" },
    don_de_la_alacridad = { "rogue_burstofspeed", "eps_bg3_haste" },
    encantar_persona = { "spell_shadow_shadowworddominate" },
    enredar = { "eps_wc3_entanglingroots" },
    golpe_ardiente = { "spell_shaman_improvelavalash" },
    golpe_furioso = { "wh_furyofasuryan" },
    golpe_llameante = { "ability_paladin_divinestorm" },
    golpe_trueno = { "spell_shaman_focusedstrikes" },
    orbe_cromatico = { "spell_frostfire orb" },
    pies_ligeros = { "spell_lifegivingspeed" },
    rayo_de_bruja = { "spell_nature_chainlightning" },
    rayo_de_enfermedad = { "eps_bg3_rayofsickness" },
    replica_infernal = { "spell:80240", "eps_bg3_fireballfel", "eps_buildershaven_gobinfo" },
    temblor_de_tierra = { "spell_shaman_earthquake" },
    trampa = { "eps_lol_kled_traponarope" },
    vida_falsa = { "spell:20707", "eps_bg3_aid", "eps_buildershaven_gobinfo" },
    vinculo_de_bestia = { "eps_bg3_dominatebeast", "ability_hunter_pet_assist" },
    duelo_obligado = { "ability_warrior_challange" },
    maldicion = { "ability_creature_cursed_03" },
    susurros_disonantes = { "eps_lol_sona_songofcelerityold" },
    agarre_de_la_muerte = { "spell_deathknight_strangulate" },
    arrepentimiento = { "spell_holy_prayerofhealing" },
    cadenas_de_hielo = { "spell_frost_chainsofice" },
    choque_elemental = { "spell_nature_elementalprecision_1" },
    drenar_vida = { "spell_shadow_lifedrain02" },
    escudo_de_relampagos = { "spell_nature_lightningshield" },
    explosion_de_cadaveres = { "ability_creature_disease_02" },
    favor_aterrador = { "ability_revendreth_deathknight" },
    fuego_estelar = { "spell_arcane_starfire" },
    fuego_interior = { "spell_holy_innerfire" },
    piel_demoniaca = { "spell_shadow_ragingscream" },
    pluma_angelica = { "ability_priest_angelicfeather" },
    proyectil_de_fuego_y_hielo = { "ability_mage_frostfirebolt" },
    toque_helado_nivel_1 = { "spell_deathknight_icetouch", "dos2_ghost13" },
    vacio_oscuro = { "inv_elemental_primal_shadow" },
    vision_mental = { "spell_holy_mindvision" },
    agrandar_reducir = { "eps_hs_pintsizepotion" },
    alterar_el_propio_aspecto = { "eps_lol_tft_shapeshifteremblem" },
    arma_espiritual = { "eps_bg3_magicweapon" },
    arma_magica = { "eps_bg3_blessweapon" },
    augurio = { "spell_monk_zenpilgrimage" },
    aura_magica_de_nystul = { "wh_corruptingretribution" },
    auxilio = { "wh_heartoffire" },
    boca_magica = { "inv_relics_runestone" },
    calentar_metal = { "eps_bg3_heatmetal" },
    calmar_emociones = { "spell_arcane_focusedpower" },
    castigo_marcador = { "spell_paladin_templarsverdict", "spell_holy_sealofwrath" },
    cerradura_arcana = { "eps_bg3_arcanelock" },
    contorno_borroso = { "d3_blur" },
    crecimiento_espinoso = { "eps_bg3_spikegrowth" },
    detectar_pensamientos = { "eps_bg3_detectthoughts" },
    detectar_trampas = { "ability_spy" },
    dulce_descanso = { "warrior_talent_icon_deadlycalm" },
    embelesar = { "spell_holy_silence" },
    esfera_de_llamas = { "inv_misc_orb_05" },
    flecha_acida_de_melf = { "spell_hunter_exoticmunitions_poisoned" },
    hacer_anicos = { "eps_lol_orianna_commandshockwave" },
    hallar_corcel = { "spell_nature_swiftness" },
    hoja_de_fuego = { "eps_lol_gangplank", "Interface\\Icons\\Spell_Fire_FlameTounge", "eps_lol_gangplank_trialbyfire" },
    imagen_multiple = { "ability_mage_massinvisibility" },
    inmovilizar_persona = { "spell_mage_overpowered" },
    invisibilidad = { "ability_mage_invisibility" },
    levitar = { "eps_bg3_levitate", "Interface\\Icons\\Spell_Holy_LayOnHands", "ability_priest_angelicfeather" },
    llama_permanente = { "eps_bg3_sacredflameelune" },
    localizar_animales_o_plantas = { "ability_druid_healinginstincts" },
    localizar_objeto = { "w3reforgedpickupitem" },
    mensajero_animal = { "eps_bg3_catattention" },
    oscuridad = { "spell_shadow_auraofdarkness" },
    pasar_sin_rastro = { "eps_bg3_cloakshadows" },
    paso_brumoso = { "eps_bg3_mistystep" },
    piel_robliza = { "spell_nature_skinofearth" },
    plegaria_de_curacion = { "eps_bg3_prayerofhealing" },
    potenciar_caracteristica = { "spell_magic_greaterblessingofkings" },
    proteccion_contra_veneno = { "hots_thebutcher_freshmeat_poison" },
    rafaga_de_viento = { "eps_bg3_gustofwind" },
    rayo_abrasador = { "eps_bg3_scorchingray" },
    rayo_de_luna = { "eps_bg3_moonbeam" },
    rayo_debilitador = { "warlock_curse_weakness" },
    restablecimiento_menor = { "spell_holy_purify" },
    silencio = { "eps_bg3_silence" },
    sordera_ceguera = { "spell_shadow_painandsuffering" },
    sugestion = { "spell_shadow_charm" },
    telarana = { "eps_bg3_conjureweb" },
    trepar_cual_aracnido = { "achievement_halloween_spider_01" },
    truco_de_la_cuerda = { "inv_misc_rope_01" },
    ver_invisibilidad = { "spell_shadow_detectinvisibility" },
    vinculo_protector = { "eps_bg3_wardingbond" },
    vision_en_la_oscuridad = { "eps_bg3_darkvision" },
    zona_de_verdad = { "smite_aurelionsol_celestialexpansion" },
    bomba_viva = { "ability_blackhand_attachedslagbombs" },
    cascara_antimagica = { "spell_shadow_antimagicshell" },
    ciclon = { "w3reforgedcyclone" },
    crear_piedra_de_salud = { "hd_create_healstone" },
    desgarrar_mente = { "eps_lol_zilean_mindtwist" },
    desvanecerse = { "spell_magic_lesserinvisibilty" },
    encadenar_no_muertos = { "ability_deathknight_deathchain" },
    enfoque_interior = { "w3reforgedinnerfire" },
    erupcion_de_lava = { "spell_shaman_lavaburst" },
    exorcismo = { "spell_holy_excorcism_02" },
    explosion_aullante = { "spell_frost_arcticwinds" },
    fortaleza_de_hielo = { "spell_deathknight_iceboundfortitude" },
    fuerza_brillante = { "eps_bg3_beaconofhope" },
    golpe_justo = { "spell_holy_crusaderstrike" },
    guardian_del_rey = { "spell_paladin_clarityofpurpose" },
    hervor_de_sangre = { "spell_deathknight_bloodboil" },
    prisma_sagrado = { "spell_paladin_holyprism" },
    toque_helado_nivel_2 = { "ability_deathknight_icygrip" },
    voluntad_interior = { "hots_cassia_innerlight" },
    acelerar = { "ability_socererking_arcaneacceleration" },
    animar_a_los_muertos = { "inv_pet_ghoul" },
    bola_de_fuego = { "spell_fire_fireball02" },
    caminar_sobre_el_agua = { "spell_frost_windwalkon" },
    circulo_magico = { "spell_arcane_blast" },
    clarividencia = { "hd_ldaeye" },
    conjurar_animales = { "spell_druid_wildcharge" },
    contrahechizo = { "eps_bg3_counterspell" },
    corcel_fantasma = { "inv_mount_spectralhorse" },
    crear_comida_y_agua = { "hd_create_conjurabletable" },
    crecimiento_vegetal = { "eps_bg3_plantgrowth" },
    desplazamiento = { "spell:1953", "eps_buildershaven_gobinfo" },
    disipar_magia = { "spell_holy_dispelmagic" },
    don_de_lenguas = { "smite_kumbhakarna_a03" },
    espiritus_guardianes = { "eps_bg3_spiritguardians" },
    forma_gaseosa = { "inv_misc_volatileair" },
    fundirse_con_la_piedra = { "spell_shadow_unholystrength" },
    glifo_custodio = { "inv_misc_rune_03" },
    hablar_con_las_plantas = { "ability_druid_serenefocus" },
    hablar_con_los_muertos = { "eps_bg3_speakwithdead" },
    imagen_mayor = { "spell_arcane_arcanetactics" },
    imponer_maldicion = { "ability_creature_cursed_04" },
    indetectable = { "w3reforgedinvisibility" },
    levantar_maldicion = { "w3reforgedcurse" },
    llamar_al_relampago = { "eps_bg3_calllightning", "eps_bg3_lightningblast" },
    luz_del_dia = { "eps_bg3_daylight" },
    muro_de_viento = { "eps_lol_rk_yasuo_windwall" },
    nube_apestosa = { "w3reforgedplaguecloud" },
    palabra_de_curacion_en_masa = { "eps_bg3_masshealingword" },
    patron_hipnotico = { "eps_bg3_hypnogaze" },
    pequena_choza_de_leomund = { "eps_lol_blitzcrank_manabarrier" },
    proteccion_contra_energia = { "inv_shield_1h_artifactstormfist_d_06" },
    ralentizar = { "d3_slowtime" },
    recado = { "ability_mage_studentofthemind" },
    relampago = { "eps_bg3_lightningbolt" },
    respirar_bajo_el_agua = { "spell_shadow_demonbreath" },
    revivir = { "eps_bg3_revivfy" },
    senal_de_esperanza = { "ability_priest_rayofhope" },
    terror = { "hd_warlock_fear" },
    toque_vampirico = { "spell_shadow_improvedvampiricembrace" },
    tormenta_de_aguanieve = { "spell_frost_ice shards" },
    volar = { "eps_bg3_fly" },
    asfixiar = { "ability_deathknight_asphixiate" },
    cadena_de_curacion = { "spell_nature_healingwavegreater" },
    cambio_de_vacio = { "spell_priest_voidshift" },
    estrella_divina = { "spell_priest_divinestar" },
    explosion_arcana_nivel_3 = { "spell_nature_wispsplode", "ability_monk_forcesphere_pink" },
    faro_de_luz = { "ability_paladin_beaconoflight" },
    horror_psiquico = { "spell_shadow_psychichorrors" },
    ira_sagrada = { "ability_paladin_sanctifiedwrath" },
    luz_cegadora = { "ability_paladin_blindinglight2" },
    manto_del_cruzado_caido = { "spell_holy_retributionaura" },
    nova_sagrada = { "ability_revendreth_deathknight", "spell_holy_holynova" },
    oleada_estelar = { "spell_arcane_arcane03" },
    pua_terrestre = { "ability_earthen_pillar" },
    robar_conjuro = { "spell_arcane_arcane02" },
    ventisca = { "d3_blizzard" },
    adivinacion = { "spell_nature_crystalball" },
    ampliar_o_disminuir_magia = { "spell_arcane_studentofmagic" },
    apariciones_sombrias = { "spell_shadow_shadesofdarkness" },
    asesino_fantasmal = { "hd_warlock_fearscream" },
    aura_de_pureza = { "wh_purify" },
    aura_de_vida = { "spell_holy_auramastery" },
    barrera_luminosa = { "eps_lol_spell_barriernew" },
    bloque_de_hielo = { "spell_frost_frost" },
    cofre_secreto_de_leomund = { "eps_lol_rk_missfortune_fotunesfavor", "Interface\\Icons\\INV_Box_01", "eps_lol_rk_missfortune_fortunesfavor" },
    compulsion = { "ability_hunter_killcommand" },
    confusion = { "d3_massconfusion" },
    conjurar_criaturas_del_bosque = { "eps_rumble_faeriedragon" },
    conjurar_elementales_menores = { "inv_pet_pandarenelemental" },
    conjurar_no_muertos = { "w3reforgedabomination" },
    controlar_agua = { "eps_lol_rk_illaoi_crashingtides" },
    descarga_arcana = { "spell_arcane_arcane01" },
    destierro = { "spell_shadow_cripple" },
    dominar_bestia = { "eps_bg3_dominatebeast" },
    dominar_no_muertos = { "inv_misc_bone_skull_01" },
    encantar_monstruo = { "hots_sylvanas_mindcontrol" },
    encontrar_corcel_mayor = { "ability_mount_dreadsteed" },
    escudo_de_fuego = { "dos2_fireshield" },
    escudo_divino = { "spell_holy_divineshield" },
    esfera_de_agua = { "spell_animaardenweald_orb" },
    esfera_de_tormenta = { "spell_broker_orb" },
    esfera_resiliente_de_otiluke = { "ability_racial_forceshield" },
    esfera_vitriolica = { "eps_arc_orbgreen" },
    fuego_y_azufre = { "ability_warlock_fireandbrimstone" },
    golpe_devastador = { "ability_warrior_savageblow" },
    guardian_de_la_fe = { "eps_bg3_guardianoffaith" },
    guardian_de_la_naturaleza = { "eps_wc3h_aquaticdruid" },
    invisibilidad_mayor = { "ability_mage_greaterinvisibility" },
    invocar_aberracion = { "ability_socererking_summonaberration" },
    invocar_demonio_mayor = { "ability_warlock_demonicpower" },
    invocar_elemental = { "spell_fire_elemental_totem" },
    invocar_entidad_del_vacio = { "inv_nzothfish_void" },
    lanza_psiquica_de_raulothim = { "eps_lol_pantheon_spearshot" },
    libertad_de_movimiento = { "rogue_burstofspeed" },
    localizar_criatura = { "inv_misc_map02" },
    marchitar = { "inv_misc_herb_12" },
    mensajero_rapido_de_galder = { "achievement_guildperk_gmail" },
    moldear_piedra = { "inv_stone_sharpeningstone_01" },
    muerte_y_decadencia = { "w3reforgeddeathanddecay" },
    muro_de_fuego = { "eps_bg3_walloffire" },
    ojo_arcano = { "eps_bg3_arcaneeye" },
    parra_atrapante = { "w3reforgedentanglingroots" },
    perdicion_elemental = { "hd_curseofelements_greenred" },
    piel_de_piedra = { "w3reforgedresistantskin" },
    plaga_devoradora = { "spell_shadow_devouringplague" },
    polimorfia = { "ability_mage_improvedpolymorph" },
    proteccion_contra_la_muerte = { "spell_holy_guardianspirit" },
    puerta_dimensional = { "inv_artifact_dimensionalrift" },
    radiancia_enferma = { "spell_animamaldraxxus_orb" },
    sabueso_de_mordenkainen = { "inv_pet_mastiff" },
    santuario_privado_de_mordenkainen = { "spell_arcane_teleportdalaran" },
    sombra_de_moil = { "spell_shadow_shadowform" },
    sumidero_gravitacional = { "hots_kaelthas_gravitylapse_purple" },
    tentaculos_negros_de_evard = { "spell_shadow_shadowfury" },
    terreno_ilusorio = { "achievement_zone_arathihighlands_01" },
    tormenta_de_hielo = { "w3reforgedblizzard" },
    vortice_de_ursol = { "spell_druid_ursolsvortex" },
    aguijon_mental = { "spell_priest_mindspike" },
    aliento_de_dragon = { "inv_misc_head_dragon_01" },
    bolsillo_de_muneca = { "inv_misc_coinbag06" },
    corona_de_locura = { "inv_helmet_01" },
    diablo_de_polvo = { "inv_misc_dust" },
    don_de_la_charla = { "achievement_halloween_smiley_01" },
    escritura_celeste = { "inv_fabric_celestial_cloth" },
    espiritu_curativo = { "shaman_pvp_ripplingwaters" },
    favor_de_la_fortuna = { "inv_misc_fortunecookie" },
    flechas_igneas = { "ability_searingarrow" },
    fuerza_fantasmal = { "spell_shaman_ancestralawakening" },
    hoja_sombria = { "inv_knife_1h_grimbatolraid_d_03" },
    latigo_mental_de_tasha = { "ability_warlock_whiplash" },
    llama_de_aganazzar = { "eps_lol_brand_pillarofflame" },
    nube_de_dagas = { "eps_bg3_cloudofdaggers" },
    objeto_inamovible = { "inv_stone_weightstone_02" },
    paso_sombrio = { "ability_rogue_shadowstep" },
    pirotecnia = { "spell_frost_fireresistancetotem" },
    puno_terrestre_de_maximiliano = { "misc_drogbartotem02" },
    rebano_de_familiares = { "w3reforgedflyingsheep" },
    sentido_de_bestia = { "eps_wc3h_direwolfacutesenses" },
    tormenta_de_bolas_de_nieve_de_snilloc = { "eps_lol_nunu_snowballbarrage" },
    viento_guardian = { "wh_windsprotection" },
    amigos_rapidos = { "eps_bg3_friends", "achievement_guildperk_everybodysfriend" },
    arma_elemental = { "inv_weapon_shortblade_98" },
    aura_de_vitalidad = { "eps_bg3_auraofvitality" },
    discurso_motivador = { "eps_lol_spell_rally" },
    enemigos_en_abundancia = { "d3_fetisharmy" },
    fingir_muerte = { "ability_rogue_feigndeath" },
    fortaleza_intelectual = { "wh_focusedmind" },
    golpe_cegador = { "ability_paladin_blindinglight" },
    hambre_de_hadar = { "eps_bg3_hungerofhadar" },
    invocar_demonios_menores = { "ability_warlock_empoweredimp" },
    invocar_no_muertos = { "spell_shadow_darksummoning" },
    invocar_sombras = { "spell_shadow_summonvoidwalker" },
    manto_del_cruzado = { "spell_holy_crusade" },
    meteoros_menores_de_melf = { "spell_fire_meteorstorm" },
    muro_de_agua = { "eps_bg3_wallofice" },
    ola_de_marea = { "eps_lol_nami_tidalwave" },
    onda_de_pulso = { "eps_lol_leesin_sonicwave" },
    parpadeo = { "wc3_blink", "spell_arcane_blink" },
    paso_de_trueno = { "ability_thunderking_overcharge" },
    sirviente_minusculo = { "eps_rumble_npcstonegolem" },
    sueno_profundo = { "smite_kumbhakarna_passive" },
    tierra_en_erupcion = { "w3reforgedvolcano" },
    torre_de_galder = { "w3reforgedguardtower" },
    transferencia_de_vida = { "spell_shadow_lifedrain" },
    explosion_lunar = { "eps_lol_aurelionsol_fallingstar" },
    rayo_del_caos = { "spell_fire_felflamebolt" },
}

if IconCatalog and IconCatalog.RegisterSpells then
    IconCatalog.RegisterSpells(BG3_ICON_CANDIDATES_BY_SPELL_ID)
end

local iconCache = {}

local function GetLibRPMedia()
    if not LibStub then return nil end
    local ok, lib = pcall(LibStub.GetLibrary, LibStub, "LibRPMedia-1.0", true)
    if ok then return lib end
end

local function ResolveIcon(iconName)
    if not iconName or iconName == "" then return nil end
    if type(iconName) == "number" then return iconName end
    if type(iconName) == "string" then
        local spellId = iconName:match("^spell:(%d+)$")
        if spellId and GetSpellTexture then
            local texture = GetSpellTexture(tonumber(spellId))
            if texture then return texture end
        end
        if iconName:match("^Interface\\") then return iconName end
    end
    if iconCache[iconName] ~= nil then return iconCache[iconName] or nil end

    local resolved
    local media = GetLibRPMedia()
    local baseLista = media and media.IsIconDataLoaded and media:IsIconDataLoaded()
    if baseLista then
        local ok, fileId = pcall(media.GetIconFileByName, media, iconName)
        if ok and fileId then
            resolved = fileId
        end
    end

    -- Solo se cachea (incluido el negativo) si la base de iconos estaba CARGADA: cachear el
    -- nil de una base aun sin registrar envenenaba ese nombre para toda la sesion.
    if baseLista then iconCache[iconName] = resolved or false end
    return resolved
end

function API.ResolveRP3IconName(iconName, fallback)
    return ResolveIcon(iconName) or fallback
end

function API.GetBG3IconName(spell)
    if not spell then return nil end
    local candidates = (IconCatalog and IconCatalog.GetSpellCandidates and IconCatalog.GetSpellCandidates(spell.id))

    if type(candidates) == "table" then
        return candidates[1]
    end
end

function API.GetSpellIcon(spell)
    if not spell then return "Interface\\Icons\\INV_Misc_Book_09" end
    local candidates = (IconCatalog and IconCatalog.GetSpellCandidates and IconCatalog.GetSpellCandidates(spell.id))

    if type(candidates) == "table" then
        for _, iconName in ipairs(candidates) do
            local resolved = ResolveIcon(iconName)
            if resolved then return resolved end
        end
    end
    return ResolveIcon(PENDING_ICON_NAME) or "Interface\\Icons\\INV_Misc_Book_09"
end






