-- HarfordDnDData: tablas de datos estaticos de la ficha D&D 5e.
-- Solo datos, sin logica. Las consume HarfordDnD.lua (y quien necesite el orden
-- canonico de caracteristicas/habilidades).

HarfordDnDData = HarfordDnDData or {}

-- Caracteristicas en orden de ficha. `key` es la clave ARC; `short` la etiqueta.
HarfordDnDData.ABIL = {
    { key = "Fuerza",       short = "FUE", desc = "Potencia física, entrenamiento atlético y capacidad para aplicar fuerza bruta.",
        saveDesc = "Resistencia frente a empujones, agarres, derribos y otros efectos que ponen a prueba la potencia física." },
    { key = "Destreza",     short = "DES", desc = "Agilidad, reflejos, coordinación y equilibrio.",
        saveDesc = "Reflejos, agilidad y rapidez para evitar peligros repentinos." },
    { key = "Constitucion", short = "CON", desc = "Salud, aguante y resistencia física.",
        saveDesc = "Aguante físico frente a venenos, enfermedades, fatiga y otras adversidades corporales." },
    { key = "Inteligencia", short = "INT", desc = "Capacidad de aprender, recordar, analizar y razonar.",
        saveDesc = "Fortaleza del razonamiento y la memoria frente a ilusiones, engaños y ataques mentales." },
    { key = "Sabiduria",    short = "SAB", desc = "Sentido común, intuición, voluntad y conciencia del entorno.",
        saveDesc = "Fuerza de voluntad y claridad mental ante el miedo, los encantamientos y la manipulación de la mente." },
    { key = "Carisma",      short = "CAR", desc = "Magnetismo personal, liderazgo, confianza y capacidad de influir en otros.",
        saveDesc = "Firmeza de la identidad y del espíritu frente a posesiones, destierros y efectos que alteran la esencia del individuo." },
}

-- Habilidades en orden de ficha. `ability` referencia una key de ABIL.
HarfordDnDData.SKILLS = {
    { name="Acrobacias", ability="Destreza", id="Acrobacias", desc="Mantener el equilibrio y realizar maniobras acrobáticas." },
    { name="Atletismo", ability="Fuerza", id="Atletismo", desc="Trepar, saltar, nadar y otras proezas físicas exigentes." },
    { name="Conocimiento Arcano", ability="Inteligencia", id="Arcano", desc="Conocimiento sobre magia, planos, objetos mágicos y tradiciones arcanas." },
    { name="Engaño", ability="Carisma", id="Engano", desc="Mentir, disfrazar la verdad y fingir." },
    { name="Historia", ability="Inteligencia", id="Historia", desc="Conocimiento de acontecimientos históricos, leyendas y civilizaciones." },
    { name="Interpretación", ability="Carisma", id="Interpretacion", desc="Actuar, cantar, bailar o entretener." },
    { name="Intimidación", ability="Carisma", id="Intimidacion", desc="Influir mediante amenazas o presencia." },
    { name="Investigación", ability="Inteligencia", id="Investigacion", desc="Deducción, búsqueda de pistas y análisis." },
    { name="Juego de Manos", ability="Destreza", id="JuegoManos", desc="Prestidigitación, ocultar objetos, hurtar bolsillos." },
    { name="Medicina", ability="Sabiduria", id="Medicina", desc="Diagnosticar heridas o enfermedades y estabilizar criaturas." },
    { name="Naturaleza", ability="Inteligencia", id="Naturaleza", desc="Conocimiento del mundo natural." },
    { name="Percepción", ability="Sabiduria", id="Percepcion", desc="Detectar detalles mediante los sentidos." },
    { name="Perspicacia", ability="Sabiduria", id="Perspicacia", desc="Leer intenciones, emociones y mentiras." },
    { name="Persuasión", ability="Carisma", id="Persuasion", desc="Convencer mediante tacto, educación o diplomacia." },
    { name="Religión", ability="Inteligencia", id="Religion", desc="Conocimiento de dioses, cultos y tradiciones religiosas." },
    { name="Sigilo", ability="Destreza", id="Sigilo", desc="Ocultarse, moverse sin ser visto ni oído." },
    { name="Supervivencia", ability="Sabiduria", id="Supervivencia", desc="Rastrear, orientarse y sobrevivir en la naturaleza." },
    { name="Trato con Animales", ability="Sabiduria", id="Animales", desc="Calmar, controlar o interpretar animales." },
}

-- ICONS: mapa nombre-de-rasgo normalizado -> icono (sin Interface\Icons\), auto-extraido
-- de los 14 perfiles TRP3. Lo usa el libro de habilidades para el icono de cada rasgo.
HarfordDnDData.ICONS = {
    ["absolucion encadenar no muertos"] = "spell_nature_slow",
    ["absorber elementos"] = "ability_shaman_echooftheelements",
    ["accion astuta"] = "ability_rogue_fleetfooted",
    ["acuajet"] = "inv_weapon_rifle_33",
    ["adaptacion salvaje"] = "eps_wow_wildstalkr",
    ["afinidad arcana"] = "ability_racial_arcaneaffinity",
    ["afinidad elemental"] = "ability_shawaterelemental_reform",
    ["afinidad feral frenesi"] = "ability_druid_primaltenacity",
    ["afinidades salvajes"] = "ability_druid_earthandsky",
    ["agarre de la muerte"] = "spell_deathknight_strangulate",
    ["ahuyentar el mal"] = "ability_paladin_turnevil",
    ["alacridad"] = "rogue_burstofspeed",
    ["alarma"] = "inv_misc_bell_green",
    ["antarbol"] = "ability_druid_treeoflife",
    ["apariencia falsa"] = "ability_druid_forceofnature",
    ["aprender hechizos"] = "spell_mage_presenceofmind",
    ["arma espiritual"] = "inv_legendary_sword",
    ["arrepentimiento"] = "spell_holy_prayerofhealing",
    ["arrollar"] = "ability_warrior_unrelentingassault",
    ["artista del escape"] = "eps_bg3_sprint",
    ["ataque furtivo"] = "ability_rogue_bladetwisting",
    ["autoridad de la orden: espada de ebano"] = "inv_jewelry_talisman_12",
    ["autoridad del capitan harford"] = "achievement_bg_3flagcap_nodeaths",
    ["auxilio"] = "eps_bg3_nightsongaidblue",
    ["bendicion"] = "eps_bg3_bless",
    ["brazos de hadar"] = "eps_bg3_armsofhadar",
    ["caida de pluma"] = "inv_feather_04",
    ["cambio de forma"] = "ability_druid_tigersroar",
    ["canalizar divinidad"] = "spell_holy_lightsgrace",
    ["carga"] = "ability_warrior_charge",
    ["castigo abrasador"] = "ability_paladin_bladeofjustice",
    ["ceremonia"] = "eps_arc_book_priest1",
    ["choque elemental"] = "ability_shaman_echooftheelements",
    ["conjuracion de hechizos"] = "ability_druid_cresentburn",
    ["conocimiento antiguo de eldre'thalas"] = "achievements_zone_azsuna",
    ["conocimientos del artifice"] = "inv_misc_enggizmos_12",
    ["controlar llamas"] = "inv_elemental_mote_fire01",
    ["copiar un conjuro al libro"] = "inv_inscription_darkmooncard_putrescence",
    ["crear fogata"] = "inv_magemount_fire",
    ["crear o destruir agua"] = "icon_petfamily_water",
    ["cuchillo de hielo"] = "ability_paladin_bladeofjusticeblue",
    ["curar heridas"] = "eps_bg3_heal",
    ["defensa sin armadura"] = "inv_leather_raiddemonhunter_q_02helm",
    ["desarme"] = "ability_warrior_disarm",
    ["descarga de fuego"] = "spell_fire_flamebolt",
    ["descarga relampago"] = "ability_vehicle_electrocharge",
    ["desgarrar mente"] = "spell_shadow_mindflay",
    ["detectar magia 1/dia"] = "ability_monk_forcesphere_arcane",
    ["detectar venenos y enfermedades"] = "spell_shadow_detectinvisibility",
    ["determinacion"] = "ability_warrior_rallyingcry",
    ["devocion"] = "spell_holy_fanaticism",
    ["disco flotante de tenser"] = "creatureportrait_nexus_floating_disc",
    ["disfrazarse"] = "ability_rogue_disguise",
    ["dos formas"] = "eps_wc3h_worgencurse",
    ["dote centinela"] = "ability_warrior_revenge",
    ["dote observador"] = "ability_eyeoftheowl",
    ["drenar vida"] = "w3reforgedlifedrain",
    ["druidico"] = "ability_druid_lunarguidance",
    ["duelo forzado"] = "eps_lol_tft_duelistemblem",
    ["ecos de fe"] = "hots_anduin_holywordsalvation",
    ["embestida"] = "ability_druid_mangle",
    ["encontrar familiar"] = "eps_bg3_callanimals",
    ["endurecido por la guerra"] = "ability_pvp_hardiness",
    ["energia"] = "ability_rogue_vigor",
    ["enmaranar"] = "inv_misc_root_01",
    ["entender idiomas"] = "inv_misc_note_05",
    ["erudito arcano"] = "spell_holy_arcaneintellect",
    ["escritura magica oculta"] = "inv_glyph_primemage",
    ["escucha resonante conejil"] = "inv_misc_rabbit_ears",
    ["escudo"] = "eps_lol_sivir_spellshield",
    ["escudo de fe"] = "eps_bg3_shieldoffaith",
    ["escudo de relampagos"] = "spell_nature_lightningshield",
    ["escudo de sangre"] = "artifactability_blooddeathknight_umbilicuseternus",
    ["espiral de la muerte"] = "spell_shadow_deathcoil",
    ["espiritu curativo"] = "spell_animaardenweald_orb",
    ["espiritu harford"] = "inv_tabard_duelersguild",
    ["espiritu humano"] = "inv_enchant_shardbrilliantsmall",
    ["espiritu mestizo"] = "inv_enchant_shardbrilliantsmall",
    ["estallido de espadas"] = "inv_throwingknife_01",
    ["estilo de combate combate con dos armas"] = "ability_dualwield",
    ["estilo de combate defensa"] = "ability_defend",
    ["estilo de combate duelo"] = "eps_lol_tft_duelistemblem",
    ["estilo de combate gran arma"] = "ability_warrior_savageblow",
    ["experto marcial"] = "ability_monk_jab",
    ["explosion mental"] = "spell_shadow_unholyfrenzy",
    ["exponer armadura"] = "ability_rogue_dismantle",
    ["favor divino"] = "ability_paladin_selflesshealer",
    ["fervor temible"] = "ability_deathknight_deathscaress",
    ["filo atronador"] = "eps_lol_item_sheen",
    ["filo de llamas verdes"] = "inv_sword_1h_broker2boss_d_01_green",
    ["fuente de magia"] = "spell_shadow_manafeed",
    ["furia"] = "ability_warrior_innerrage",
    ["fusion con las sombras"] = "ability_racial_shadowmeld",
    ["garra"] = "eps_wc3_eattree",
    ["garrote"] = "ability_rogue_garrote",
    ["gato"] = "ability_druid_catform",
    ["generador de luz hiperorganica"] = "inv_misc_enggizmos_24",
    ["golpe de escarcha"] = "spell_deathknight_empowerruneblade2",
    ["golpe del cruzado"] = "inv_sword_08",
    ["golpe heroico"] = "ability_warrior_punishingblow",
    ["golpe runico"] = "achievement_dungeon_icecrown_frostmourne",
    ["gourmet"] = "pandarenracial_gourmand",
    ["guardia de cuchillas"] = "eps_lol_rk_ahri_ward",
    ["guia"] = "eps_bg3_combatguidance",
    ["guia ancestral"] = "ability_shaman_ancestralguidance",
    ["hablar con bestias"] = "eps_bg3_speakwithanimals",
    ["heroismo"] = "ability_shaman_heroism",
    ["himno divino"] = "ability_priest_heavanlyvoice",
    ["identificar"] = "eps_bg3_identify",
    ["ilusion menor"] = "spell_magic_lesserinvisibilty",
    ["imposicion de manos"] = "spell_holy_layonhands",
    ["infligir heridas"] = "eps_bg3_inflictwounds",
    ["iniciacion illidari"] = "ability_demonhunter_eyeofleotheras",
    ["intrepido"] = "ability_warrior_revenge",
    ["investigador"] = "w3reforgedarcanescroll",
    ["ira"] = "ability_warrior_innerrage",
    ["kalimag"] = "eps_lol_taliyah_unraveledearth",
    ["lechucico lunar"] = "ability_druid_improvedmoonkinform",
    ["legado del vacio"] = "hots_malzahar_voidshift",
    ["legado elficocrear fogata"] = "achievement_zone_eversongwoods",
    ["legado thalassianoreparar"] = "achievement_zone_eversongwoods",
    ["libro de conjuros"] = "garrison_building_magetower",
    ["llama sagrada"] = "eps_bg3_sacredflameholy",
    ["llama vil"] = "eps_bg3_fireballfel",
    ["llamado divino sagrado"] = "ability_paladin_holyavenger",
    ["llamas del caos"] = "spell_fire_felfire",
    ["localizar objeto"] = "inv_misc_spyglass_03",
    ["luz"] = "eps_lol_leona_sunlightold",
    ["magia vil"] = "eps_wc3h_felpower",
    ["mano de mago"] = "eps_bg3_magehand",
    ["manos ardientes"] = "eps_bg3_flamingfist",
    ["maquina de matar"] = "inv_sword_122",
    ["marca de ursoc"] = "eps_lol_volibear_frenzyold",
    ["mascara de lo salvaje"] = "ability_ambush",
    ["mejoras mecanicas"] = "inv_mechagon_wrench",
    ["mensaje"] = "achievement_guildperk_gmail",
    ["metamorfosis"] = "ability_demonhunter_metamorphasisdps",
    ["misivas secretas"] = "archaeology_5_0_changkiboard",
    ["modo de mantenimiento"] = "ability_siege_engineer_automatic_repair_beam",
    ["momentum"] = "ability_demonhunter_doublejump",
    ["mordida"] = "inv_misc_monsterfang_02",
    ["mordida de demonio"] = "ability_demonhunter_torment",
    ["mordisco"] = "inv_misc_monsterfang_02",
    ["multiataque"] = "ability_druid_mangle2",
    ["mutilar"] = "ability_rogue_shadowstrikes",
    ["nube de oscurecimiento"] = "spell_holiday_tow_spicecloud",
    ["oido y olfato agudo"] = "ability_shaman_freedomwolf",
    ["oidos atentos"] = "inv_misc_ear_human_01",
    ["olfato agudo"] = "ability_hunter_catlikereflexes",
    ["omniherramienta"] = "inv_axe_1h_mechagnome_c_01",
    ["orden imperiosa"] = "ability_warrior_rallyingcry",
    ["orden oscura"] = "spell_nature_shamanrage",
    ["oso"] = "ability_racial_bearform",
    ["palabra de curacion"] = "eps_bg3_healingword",
    ["palabra de las sombras dolor"] = "spell_shadow_shadowwordpain",
    ["palabra de las sombras muerte"] = "spell_shadow_demonicfortitude",
    ["palma fulminante"] = "pandarenracial_quiveringpain",
    ["paz interior"] = "pandarenracial_innerpeace",
    ["perdicion"] = "ability_creature_cursed_03",
    ["pericia"] = "ability_rogue_stayofexecution",
    ["pico"] = "inv_misc_birdbeck_01",
    ["piedad con los moribundos"] = "ability_pvp_defenderoftheweak",
    ["piel demoniaca"] = "spell_shadow_ragingscream",
    ["plegaria de curacion"] = "eps_bg3_prayerofhealing",
    ["poder runico"] = "spell_shadow_rune",
    ["poder totemico corriente purificadora"] = "inv_spear_04",
    ["poder totemico marea viva"] = "spell_nature_riptide",
    ["poder totemico resistencia elemental"] = "ability_shaman_multitotemactivation",
    ["posicion de privilegio"] = "eps_wc3h_evilhumanqueen",
    ["potenciar protecciones"] = "ability_demonhunter_empowerwards",
    ["presencia retorcida"] = "achievement_explore_argus",
    ["prestidigitacion"] = "spell_arcane_arcanepotency",
    ["proteccion contra el bien y el mal"] = "eps_bg3_heavilyarmored",
    ["proteccion mental"] = "hd_ldaknowledge",
    ["protocolo de emergencia"] = "inv_misc_enggizmos_27",
    ["purificar comida y bebida"] = "inv_misc_food_100",
    ["racha de calor"] = "ability_ironmaidens_grapeshotblast",
    ["rapidez feral"] = "ability_druid_dash",
    ["renacer oscuro"] = "eps_wc3_deathknight",
    ["reparar"] = "ability_repair",
    ["reprension infernal"] = "ability_warlock_inferno",
    ["reserva de furia"] = "ability_warrior_focusedrage",
    ["resiliencia vil"] = "eps_wc3h_felwither",
    ["resistencia"] = "eps_bg3_resistance",
    ["restablecimiento menor"] = "spell_holy_renew",
    ["reversion de conjuros"] = "eps_bg3_counterspell",
    ["salto"] = "eps_bg3_longjump",
    ["salto de pie"] = "eps_bg3_jump",
    ["secretos profanos"] = "spell_warlock_demonbolt",
    ["segundo aliento"] = "ability_hunter_harass",
    ["sentido divino"] = "spell_holy_heroism",
    ["sentido magico"] = "spell_holy_magicalsentry",
    ["sentidos agudos"] = "eps_wc3_nightelfcharm",
    ["sirviente invisible"] = "w3reforgedinvisibility",
    ["susurro de plantas"] = "ability_druid_nourish",
    ["taumaturgia"] = "ability_mage_incantersabsorbtion",
    ["tocar a los muertos"] = "eps_bg3_howlofdead",
    ["toque de vida"] = "ability_warlock_mortalcoil",
    ["toque helado"] = "spell_deathknight_icetouch",
    ["tormenta divina"] = "ability_paladin_divinestorm",
    ["totemista"] = "ability_shaman_totemrelocation",
    ["vacio oscuro"] = "hots_velkoz_voidrift",
    ["veredicto del templario"] = "spell_paladin_templarsverdict",
    ["vida entre sombras"] = "spell_rogue_shadow_reflection",
    ["vil"] = "eps_wc3h_felpact",
    ["vision en la oscuridad"] = "eps_bg3_darkvision",
    ["vision en la oscuridad superior"] = "eps_bg3_darkvision",
    ["vision espectral"] = "ability_demonhunter_eyebeam",
    ["vista aguda"] = "ability_druid_healinginstincts",
    ["vista de penumbra"] = "eps_bg3_darkvision",
    ["voz psiquica"] = "inv_hivemind",
    ["zancada prodigiosa"] = "eps_bg3_dash",
}

local function NormIconKey(v)
    v = tostring(v or ""):lower():gsub("[_%-]+", " ")
    v = v:gsub("\195[\129\161\128\160\132\164\130\162]", "a"):gsub("\195[\137\169\136\168\139\171\138\170]", "e")
    v = v:gsub("\195[\141\173\140\172\143\175\142\174]", "i"):gsub("\195[\147\179\146\178\150\182\148\180]", "o")
    v = v:gsub("\195[\154\186\153\185\156\188\155\187]", "u"):gsub("\195[\145\177]", "n")
    return (v:gsub("^%s+", ""):gsub("%s+$", ""))
end

-- Devuelve la ruta de icono (Interface\Icons\<X>) para un nombre de rasgo, o nil si no hay.
-- Match: exacto normalizado; si falla, una clave del mapa que EMPIECE por el nombre del rasgo
-- (ej. "Estilo de Combate" -> "estilo de combate gran arma"). El libro cae a un icono generico.
function HarfordDnDData.GetIcon(name)
    local k = NormIconKey(name)
    if k == "" then return nil end
    local id = HarfordDnDData.ICONS[k]
    if not id then
        for mapKey, mapIcon in pairs(HarfordDnDData.ICONS) do
            if mapKey:find(k, 1, true) == 1 then id = mapIcon; break end
        end
    end
    return id and ("Interface\\Icons\\" .. id) or nil
end
